### ISSUE TITLE
Enhancement request: Email integration

### ISSUE THREAD

**Issue by coladams** [bricelam/ImageResizer#101]
Great program! I'm using this to resize groups of photos for attaching to emails.  I imagine others may be doing the same so wondered if maybe it could integrate with email programs (like Windows Mail) to resize pictures and attach them to a blank email?  Personally I wouldn't want to keep the resized pictures after sending so ideally it would resize to a temporary folder, attach to email and then delete the temporary folder.

**Comment by JNavas2** [comment]
That kind of thing is better done in the email program or in the cloud:
* It's difficult to support integration with the different email options in use.
* In the case of [Thunderbird](https://www.thunderbird.net/en-US/) (recommended), see the [Auto Resize Image add-on](https://addons.mozilla.org/en-US/thunderbird/addon/auto-resize-image/).
* It's more efficient to share cloud (Microsoft OneDrive, Google Drive, etc) folders than to email attachments.
* See [Send Google Drive attachments in Gmail](https://support.google.com/mail/answer/2487407?hl=en&ref_topic=7280128).
* If you must use attachments with webmail (Gmail, Office 365), [Affixa](https://www.affixa.com/desktop/) can resise automatically.


_"If the only tool you have is a hammer, you will see every problem as a nail."_ —Abraham Maslow
