### ISSUE TITLE
Recycling dialog flickering during resizing

### ISSUE THREAD

**Issue by ajsgray** [bricelam/ImageResizer#107]
First of all thank you for an amazing tool!

I haven't had any problems with ImageResizer until I installed the last update, but now when I use it the Windows recycling dialog flickers constantly rendering my computer virtually unusable while the resizing is in progress.

Is this a bug or something I've done wrong?

![image resizer recycling bug](https://user-images.githubusercontent.com/17749285/41498286-e28b548c-7169-11e8-8317-c48dbaf57d12.jpg)

**Comment by bricelam** [comment]
This may be fixed in version 3.1.1. Have you tried that version?

**Comment by bricelam** [comment]
## Moved to Microsoft PowerToys

All future bug fixes, enhancements, and releases of Image Resizer for Windows will be done as part of the Microsoft PowerToys project.

If this is still something you'd like to see done, please follow up on [microsoft/PowerToys](https://github.com/microsoft/PowerToys)
