### ISSUE TITLE
Crashes explorer on Windows 10 

### ISSUE THREAD

**Issue by justinbacle** [bricelam/ImageResizer#108]
After install of version 3.1.1 explorer hangs on startup.

The program explorer.exe version 10.0.17134.1 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.
 Process ID: 1368
 Start Time: 01d407a98884e410
 Termination Time: 0
 Application Path: C:\Windows\explorer.exe
 Report Id: 454505c1-a2e1-4d4a-93f1-92381961b9a3
 Faulting package full name: 
 Faulting package-relative application ID: 
Event ID 1002

**Comment by Gerderber** [comment]
I've had this happen each of the 2 times I tried to install the update.

**Comment by bricelam** [comment]
## Moved to Microsoft PowerToys

All future bug fixes, enhancements, and releases of Image Resizer for Windows will be done as part of the Microsoft PowerToys project.

If this is still something you'd like to see done, please follow up on [microsoft/PowerToys](https://github.com/microsoft/PowerToys)
