### ISSUE TITLE
Make pictures smaller but not larger

### ISSUE THREAD

**Issue by bucmic** [bricelam/ImageResizer#109]
What does that option mean? When I have a look at the code, making smaller means shrinking (file size). Why not larger? Maybe this is a little bit misleading.

**Comment by bricelam** [comment]
It means if you specify a size like 10x10, it won't enlarge an image that's 5x5, but it will shrink an image that's 20x20.

**Comment by bricelam** [comment]
It will only reduce the resolution of images, not increase it.

**Comment by bricelam** [comment]
It's there because increasing the size usually makes images look worse.

**Comment by JNavas2** [comment]
Usually? LOL

**Comment by bricelam** [comment]
Hey, some people may be going for that fuzzy pixelated look... Art is art.

**Comment by JNavas2** [comment]
Touché

**Comment by bricelam** [comment]
## Moved to Microsoft PowerToys

All future bug fixes, enhancements, and releases of Image Resizer for Windows will be done as part of the Microsoft PowerToys project.

If this is still something you'd like to see done, please follow up on [microsoft/PowerToys](https://github.com/microsoft/PowerToys)
