### ISSUE TITLE
Add version indication somewhere in the GUI

### ISSUE THREAD

**Issue by cjnaz** [bricelam/ImageResizer#111]
My previously installed version tells me that there is a new version, but I can't tell what version I'm currently running.  Please add the current version info on the main pop-up GUI, and within the install tool GUIs.  Possibly also make the version info clear the install directory, or perhaps document where/how to find the version info (.exe file right click > Properties > Details).  If I'm missing the obvious, pardon me.

And thank you greatly for the tool.

**Comment by JNavas2** [comment]
Click _Advanced Options_, then _About_.

**Comment by cjnaz** [comment]
Never mind.  In Version 3.1.1 the Advanced menu is implemented, and the version info is right there on the About tab.  (As @JNavas2 just pointed out.)
