### ISSUE TITLE
Error: Too much metadata changed.

### ISSUE THREAD

**Issue by eyerah85** [bricelam/ImageResizer#112]
The application doesn't seem to be working for me.  I keep getting an error message that says "Commit unsuccessful because too much metadata changed".

Can anyone help me determine what the problem is?  This is a very helpful application, and I hope to continue using it.

**Comment by JNavas2** [comment]
1. Which version of the app?
2. Which version of Windows?
3. Can you provide a sample image?

**Comment by eyerah85** [comment]
![20180719_131129](https://user-images.githubusercontent.com/42043353/43602019-467a135a-967e-11e8-8c56-0e13a79a8c91.jpg)

Here is a sample image. I am using Windows 7.  I am not sure what version of the program I am using.  I am not sure how to check.  I am trying to figure it out.

**Comment by eyerah85** [comment]
Yes.  That worked.  Thank you.
