### ISSUE TITLE
Windows Server 2016 & Access Denied Messages

### ISSUE THREAD

**Issue by BluegrassCat** [bricelam/ImageResizer#113]
Hi, first let me say, we love this product.

We were going to use it to replace the now no longer distributed Microsoft Picture Manager as all we used it for was resizing pictures.

We were going to put it in our Xenapp farm on Server 2016.  However, we are experiencing the following issue:

- Resizes as it should.
- When option is selected "Resize the original pictures (don't create copies) we get an access denied message.
- This happens whether the user is an admin or standard user.
- I assume this is happening due to a temp location issue but I am unsure where that is.
- We can delete the originals manually but not having to would be much better.

Thanks,

BGC

**Comment by JNavas2** [comment]
What version of the app?
If not 3.1.1, uninstall it, reboot, and then install 3.1.1.

**Comment by BluegrassCat** [comment]
@JNavas2 - I attempted 3.1.1 on a clean machine but it has the same results.

Installed 3.0 on a clean machine and it works.  However, it throws the message there is an update.  These machines will be non-persistent so users would have to contend with it unless there is a flag to suppress update adverts.

Thx., BGC

**Comment by JNavas2** [comment]
- What version of Windows?
- Standard account or Admin account?
- Did you try uninstalling, rebooting, then reinstalling?

**Comment by BluegrassCat** [comment]
The issue occurs on:

- Windows Server 2016
- Windows 10 1803 - We don't have other Windows 10 levels to test against at the moment.
- Yes on question three.  Even reverted my snapshot to a completely clean state.

**Comment by BluegrassCat** [comment]
Any other thoughts on this application?  I am happy to deploy version 3.0 but would need to suppress the upgrade notification.  I can't seem to get around the access denied message on 3.11.  Again, the account has rights to and can delete files in that directory.  It just doesn't work using the resizer app.

Thanks!

**Comment by bricelam** [comment]
If you find out exactly what's causing the access violation, I'd be happy to look into alternatives. Unfortunately, without that information, I'm afraid I can't help much here...

**Comment by bricelam** [comment]
Is there anything in the event logs or setup logs?

**Comment by BluegrassCat** [comment]
Correct,

Installing is fine.  Just when I am replacing the file, it won’t delete the source file.  I get an access is denied message.  I can manually delete it but the imageresizer won’t for some reason.  Version 3 works like a champ, just get the upgrade notification which we would need to suppress for our users as this would be installed in a non-persistent VDI environment.

Thanks,


Mark Detrick
Director of IT
Road & Rail Services, Inc.
502.365.5357

**Comment by JNavas2** [comment]
1. Have you followed the Issue 1 troubleshooting steps in ["Access Denied" or other errors when you access or work with files and folders in Windows](https://support.microsoft.com/en-us/help/2623670/access-denied-or-other-errors-when-you-access-or-work-with-files-and-f)?
2. You can probably find out what's causing the access violation with [Process Monitor](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon).

**Comment by BluegrassCat** [comment]
@JNavas2 

1.  No, but I can delete the file manually, just not with the application option to delete when resizing.
2.  I had thought about process monitor, will look at it and see if it sheds light.  I am assuming there is a temp location being called to do the work that has the permission issue but not sure about that.  Is there a known temp location other than %temp% that the application calls to do its work?

**Comment by bricelam** [comment]
Looks like the only significant difference is using `File.Replace` instead of `File.Move`.


3.0.0
=====
``` csharp
encoder.Save(destinationStream);
FileSystem.DeleteFile(finalPath, UIOption.OnlyErrorDialogs, RecycleOption.SendToRecycleBin);
File.Move(destinationPath, finalPath);
```

3.1.1
=====
``` csharp
encoder.Save(outputStream);
File.Replace(path, _file, backup, ignoreMetadataErrors: true);
FileSystem.DeleteFile(backup, UIOption.OnlyErrorDialogs, RecycleOption.SendToRecycleBin);
```

**Comment by bricelam** [comment]
Hmm... Replace sounds more correct. Are the files read-only? If so, I'd say the old behavior was wrong.

**Comment by bricelam** [comment]
(The different volumes comment sounds like a red herring since the files should always be siblings)

**Comment by BluegrassCat** [comment]
Brice,

I have full control security on files.  They are not on a share, just local access so only NTFS permissions are applying.

Not sure about the other comment you were referring to & the red Herring.

I am not a coder so some of the particulars get lost on me.  I am able to replicate the issue with 3.11 and getting access denied when the option to resize original picture(don’t create copies) is selected.  I creates the copy but doesn’t remove the original.

Thanks!

**Comment by bricelam** [comment]
But are the files read-only?

![image](https://user-images.githubusercontent.com/1226749/44739127-cff6fd00-aaab-11e8-8bee-25c515c71e34.png)

**Comment by BluegrassCat** [comment]
Oh, well, wow.  I am a little embarrassed now.  I don't think I have had to consider that attribute in over a decade or longer.  But that was it.  We had grabbed 4 test photos from a share and just kept using the same ones over and over again.

That was it.  Thanks for the help and sorry for the back and forth.
