### ISSUE TITLE
Checkbox "Make pictures smaller but not larger" bug

### ISSUE THREAD

**Issue by Ruslan-Aleev** [bricelam/ImageResizer#114]
If the checkbox "Make pictures smaller but not larger" is checked - resize with "Custom" size does not work.

Windows 7

**Comment by JNavas2** [comment]
Works fine here on Windows 8.1.
Make sure:
1. The _latest version_ of ImageResizer is installed.
2. Your Custom size really _is_ smaller.

**Comment by Ruslan-Aleev** [comment]
@JNavas2 Sorry, my mistake, updated the program - now it works. Thanks.

**Comment by bricelam** [comment]
Duplicate of #73
