### ISSUE TITLE
Windows 10, 64 Bit, no context entry

### ISSUE THREAD

**Issue by claudiobertsch** [bricelam/ImageResizer#115]
I have the same Problem like
https://github.com/bricelam/ImageResizer/issues/21
But i think the issues is not done.
OS: Windows 10 64 Bit
ImageResizer Version 3.1.1.
No Entry in Context Menu... Checked with CCleaner... There is the Entry...
Installed WOW64 (32-Bit) Menu... There is the Entry also...

Uninstalled many times... Rebooted many times...
Installed normal, installed as Admin...

I do not know what to try... Please help me :-(

**Comment by JNavas2** [comment]
1. Has it ever worked for you? If so, what changed?
2. Which edition, version, and build of Windows 10? ([link](https://www.ilicomm.com/how-to-find-out-which-build-and-version-of-windows-10-you-have/))
3. What type (jpeg, png, ...) of image file? _Please attach a sample to your reply._
4. Have you tried going back to an earlier build of Windows 10? ([link](https://www.laptopmag.com/articles/reset-windows-10-pc))
5. Have you tried a Reset of Windows 10?

**Comment by claudiobertsch** [comment]
I have now tried to create a completely new user account. Even with the new account it does not work.

**Comment by JNavas2** [comment]
That was unlikely to work. 
Your best bets are 4 and 5 in my earlier message.

**Comment by claudiobertsch** [comment]
I found a workaround,... Version 2.1 works :-)
Its crazy...

**Comment by bricelam** [comment]
Anything unusual in Event Viewer after right-clicking?

**Comment by JNavas2** [comment]
[6 Ways to Open Event Viewer in Windows 10](https://www.isunshare.com/windows-10/6-ways-to-open-event-viewer-in-windows-10.html)

**Comment by bricelam** [comment]
## Moved to Microsoft PowerToys

All future bug fixes, enhancements, and releases of Image Resizer for Windows will be done as part of the Microsoft PowerToys project.

If this is still something you'd like to see done, please follow up on [microsoft/PowerToys](https://github.com/microsoft/PowerToys)
