### ISSUE TITLE
Filename Field Used As Part Of Source When Resized

### ISSUE THREAD

**Issue by joshhuggins** [bricelam/ImageResizer#118]
First off thanks for keeping Image Resizer going, it's invaluable for quick, on the fly resizing!

If I am resizing the following image;
**_D:\Photos\Bob.jpg_**

When I have the following value in the Filename field;
**_Resized\\%1_**

When I run the resize, I get the following message for each image I had selected;
**_Could not find a part of the path 'D:\Photos\Resized\Bob.jpg'._**

Seems like it's applying the filename field to the path it's using to locate the file somehow, or am I using incorrect syntax needed for the filename path? Thanks again!

**Comment by bricelam** [comment]
I didn't anticipated directories in that field. 😄 With a few changes, it could probably be made to work.

You can accomplish something similar by just using **%1**. Create the **Resized** directory before resizing, right-click-and-drag (Read that again. You've probably never performed this gesture.) the files into the directory and select **Resize pictures here**.

**Comment by joshhuggins** [comment]
Ahh, no worries. And nope, never tried the right click drag and drop, but that works great. Thanks for the tip!

**Comment by bricelam** [comment]
I like to think of it as arcane black magic. Works with [7-Zip](https://www.7-zip.org/) too.
