### ISSUE TITLE
Cant resize as square pic

### ISSUE THREAD

**Issue by robertkuba3** [bricelam/ImageResizer#119]
i have used older version of the program after update on 3.1.1 i cant resize picture from for example 1200x600 to 500x500 pixsels program automaticaly set it to for example 500x250 i need to change aspect ratio to the square.
how can i set it please? thank you

**Comment by JNavas2** [comment]
It sounds like you want to _crop_ or _distort_, not just resize, which preserves aspect ratio.
ImageResizer does not crop or distort. For that try [IrfanView](https://www.irfanview.com/).

**Comment by bricelam** [comment]
![image](https://user-images.githubusercontent.com/1226749/50357787-ff72bf00-050b-11e9-80c6-8e6b2e1f2757.png)

Use Fill (crops) or Stretch.
