### ISSUE TITLE
Feature Request : Fill image with color when resizing small image to large image

### ISSUE THREAD

**Issue by nugrostea** [bricelam/ImageResizer#122]
Feature Request : Fill image with color when resizing small image to large image
![1](https://user-images.githubusercontent.com/47020245/51725807-e0c99000-2096-11e9-8c51-fd3b8a269fdc.jpg)

**Comment by JNavas2** [comment]
So you just want to add a colored border, not actually resize the image?

**Comment by JNavas2** [comment]
OK, but that's not really _resizing_ the image, the purpose of this utility.

**Comment by nugrostea** [comment]
Thanks, it will be a nice feature, just like fastone photo resizer

**Comment by bricelam** [comment]
## Moved to Microsoft PowerToys

All future bug fixes, enhancements, and releases of Image Resizer for Windows will be done as part of the Microsoft PowerToys project.

If this is still something you'd like to see done, please follow up on [microsoft/PowerToys](https://github.com/microsoft/PowerToys)
