### ISSUE TITLE
Disable "Update Available" pop up

### ISSUE THREAD

**Issue by marendaweth** [bricelam/ImageResizer#123]
Is there a way by installation command or reg setting or other to disable "Update Available" pop up, e.g. configure "Don't show this message again" by command and not being forced to tick it manually?

**Comment by marendaweth** [comment]
Oh.. will check to upgrade to the latest version then! Thanks :)

**Comment by bricelam** [comment]
lol, glad there’s at least one compelling reason to update

**Comment by bricelam** [comment]
## Moved to Microsoft PowerToys

All future bug fixes, enhancements, and releases of Image Resizer for Windows will be done as part of the Microsoft PowerToys project.

If this is still something you'd like to see done, please follow up on [microsoft/PowerToys](https://github.com/microsoft/PowerToys)
