### ISSUE TITLE
enhancement suggestion : recusrsive folder option

### ISSUE THREAD

**Issue by Themoney777** [bricelam/ImageResizer#126]
Hi

I have lots of folder so i would like to be able to select the parent folder and start resizing all pictures in all subfolders.

Thank you =)

**Comment by JNavas2** [comment]
+1

**Comment by steveroot** [comment]
Workaround: You can use windows built in search to find all the images below the current directory then use ImageResizer as normal (CTRL-A to select all, right click one to bring up the context menu option to resize)

![search-example1](https://user-images.githubusercontent.com/219903/53179114-0476ec00-35eb-11e9-9383-732331d59200.jpg)

Search box is top right of window. Searching for *.jpg includes all subdirectories

![search-example2](https://user-images.githubusercontent.com/219903/53179140-0b9dfa00-35eb-11e9-8e1d-b6c031132ea1.jpg)

Not my best ever screen shot, but hopefully that helps readers find the search box :-)

**Comment by JNavas2** [comment]
Good suggestion.
More thorough search with "kind:=picture" (unless you want just "*.jpg").

**Comment by bricelam** [comment]
This functionality is outside the scope of this utility. Image Resizer aims to extend File Explorer which, as shown, already has good, recursive searching and selecting abilities.
