### ISSUE TITLE
Disable check for update

### ISSUE THREAD

**Issue by cesco69** [bricelam/ImageResizer#128]
I'm behind a proxy firewall without internet access, ImageResizer take over 10 seconds to open because try to check if there are new update.

There is an option for disable check for update?

**Comment by JNavas2** [comment]
Suggestions:
1. Check for update in non-blocking thread.
2. Ability to change update check frequency between daily, weekly, monthly.

**Comment by bricelam** [comment]
Versions 3.1.0 and newer don't check for updates. Given how frequently I release (yearly at best) the value of checking seemed pretty low. For those who still care, GitHub lets you subscribe to new release notifications.

**Comment by cesco69** [comment]
@bricelam i have latest version... why it take 10 seconds to open? it seem make something with network...

**Comment by JNavas2** [comment]
Which version of Windows?
I think IR uses .NET, and your issue may be related to .NET:
1. Make sure all updates have been applied to Windows and .NET frameworks.
2. Check that with the [.NET Framework Setup Verification Tool](https://blogs.msdn.microsoft.com/astebner/2008/10/13/net-framework-setup-verification-tool-users-guide/).
3. Try the [Microsoft .NET Framework Repair Tool](https://support.microsoft.com/en-us/help/2698555/microsoft-net-framework-repair-tool-is-available).
