### ISSUE TITLE
remove/replace characters from source filename

### ISSUE THREAD

**Issue by Pfeifakopf** [bricelam/ImageResizer#129]
For example, you have files with the a filename like filename_1200px.jpg it would be great, to change the name directly to filename_960px.jpg .

**Comment by bricelam** [comment]
Interesting. We could try to determine if the original is already in the filename format and extract just the base name if so. Sounds handy.

**Comment by bricelam** [comment]
## Moved to Microsoft PowerToys

All future bug fixes, enhancements, and releases of Image Resizer for Windows will be done as part of the Microsoft PowerToys project.

If this is still something you'd like to see done, please follow up on [microsoft/PowerToys](https://github.com/microsoft/PowerToys)
