### ISSUE TITLE
Automating Conversion without opening the dialogue box? 

### ISSUE THREAD

**Issue by saiftheboss7** [bricelam/ImageResizer#130]
Love the program. However, just a feature request. I already have configured the program as my preference. I do not need the extra click "Resize Images". I would love even more if the image gets resized automatically after I click "Resize image". Essentially, will give me a faster workflow.

**Comment by bricelam** [comment]
Similar scenario as #14 would enable

**Comment by bricelam** [comment]
## Moved to Microsoft PowerToys

All future bug fixes, enhancements, and releases of Image Resizer for Windows will be done as part of the Microsoft PowerToys project.

If this is still something you'd like to see done, please follow up on [microsoft/PowerToys](https://github.com/microsoft/PowerToys)
