### ISSUE TITLE
Feature Request: Flipping Images

### ISSUE THREAD

**Issue by apoorva2398** [bricelam/ImageResizer#131]
Is it possible to add flipping images (horizontally and vertically)? Windows already includes rotating by default.

**Comment by bricelam** [comment]
There used to be a hack where specifying a negative size would flip the image. Not sure if it still works...

**Comment by bricelam** [comment]
Try -100 percent and see what it does...

**Comment by apoorva2398** [comment]
Yes, that flips it horizontally. Thank you!

**Comment by bricelam** [comment]
lol, awesome. Someone once tried to tell me it was a bug, and I’m like, “What else could you possibly be trying to do by entering a negative size?”
