### ISSUE TITLE
Stopped Working

### ISSUE THREAD

**Issue by vanwalle** [bricelam/ImageResizer#133]
Windows 10, just stopped working.  I notice a .NET runtime error 1026 each time I try to resize.  Have done the uncheck .NET 4.7, reboot, recheck, reboot, but that does not seem to resolve.  Have also uninstalled the software, and download fresh copy and reinstall.  Still same.

Any suggestions?

![2019-04-16_11-25-22](https://user-images.githubusercontent.com/49688839/56222722-85c28c00-603a-11e9-8f5f-9b5ec57e997b.gif)
![2019-04-16_11-26-19](https://user-images.githubusercontent.com/49688839/56222723-85c28c00-603a-11e9-9037-196fbbffc2de.gif)

**Comment by JNavas2** [comment]
1. Does this affect all images, or just certain images?
2. Have you recently applied Windows Updates?
3. Have you tried going back to a Restore Point?
4. Have you run anti-malware scans?

**Comment by vanwalle** [comment]
Thank you. I will try all those and report back.

**Comment by bricelam** [comment]
Also try deleting `%LOCALAPPDATA%\Brice_Lambson\ImageResizer.exe_Url_blahblahblahblahblahblahblahblah\3.1.1.0\user.config` (note, the directory isn't actually named *blahblahblah*)

**Comment by vanwalle** [comment]
Hi. Had to move to another solution, sorry. Was taking too much effort to
resolve. Thank you though.
