### ISSUE TITLE
New 3.1.2 Download?

### ISSUE THREAD

**Issue by geekmaster64** [bricelam/ImageResizer#134]
Hello, 

It appears that 3.1.2 was created awhile back but the 3.1.1 download is the current available build. is there a 3.1.2 download available?  I honestly don't know how to do the build on my machine.

Thank you for your help!

**Comment by JNavas2** [comment]
3.1.1 is the latest actual Release:
https://github.com/bricelam/ImageResizer/releases

**Comment by geekmaster64** [comment]
My apologies!
