### ISSUE TITLE
Program window doesn't appear after right-click

### ISSUE THREAD

**Issue by Blencathr4** [bricelam/ImageResizer#136]
Windows 10 Pro, Dell Latitude 7424 laptop.

It worked fine to start with, after imaging a brand new machine from our master image and installing a couple of extra programs (including ImageResizer). Everything tested out fine, A few days later as I was getting ready to roll it out - yesterday - I installed another bunch of Windows updates, added a couple more programs (Avidemux, Shotcut), now after selecting 'Resize Pictures' in the context menu, the Image Resizer window does not appear. The wait cursor appears for a second or so, then nothing. Event viewer shows the attached info.

I tried uninstalling the latest set of Windows updates, no change. I tried re-imaging the laptop again, still nothing. Went down to v3.0, no change. Will try on different laptop next (exactly same specs), then try some earlier program versions.

[imageresizer error.txt](https://github.com/bricelam/ImageResizer/files/3405782/imageresizer.error.txt)

Edit to add: tried on different laptop. After activation: worked OK. After imaging: worked OK. After fully updating Windows 10 - doesn't work. I think I may have attached the wrong line in the event viewer last time, so here's the error from this new laptop.

[imageresizer error -2.txt](https://github.com/bricelam/ImageResizer/files/3406855/imageresizer.error.-2.txt)

**Comment by JNavas2** [comment]
Did you try rolling back with System Restore (or other backup) to see if that fixes the problem?

**Comment by Blencathr4** [comment]
I forgot about that. Using 'Reset this PC' did fix the problem on the first laptop. Re-installing everything I had/need again didn't cause the issue to re-appear... yet. I don't really understand that one. Made a backup, and will image this one and deploy to the second (which does still have this issue) and see what happens there I guess.

Thank you for your help.

**Comment by Snurfp** [comment]
I have the same problem - Windows 10 Pro, version 1803, build 17134.885.
Installation program is successful. 
I can run C:\Program Files (x86)\Image Resizer for Windows\ImageResizer.exe. 
But I can't run program from Explorer.  After right-click any picture in Explorer  I can't run program (no dialog appears). 

Thank you for your help

**Comment by bricelam** [comment]
## Moved to Microsoft PowerToys

All future bug fixes, enhancements, and releases of Image Resizer for Windows will be done as part of the Microsoft PowerToys project.

If this is still something you'd like to see done, please follow up on [microsoft/PowerToys](https://github.com/microsoft/PowerToys)
