### ISSUE TITLE
Set maximum file size based on JPG compression

### ISSUE THREAD

**Issue by mikes2nd** [bricelam/ImageResizer#137]
So I need all files resized to under 250k.  I typically will use medium and then play with the jpg compression.  It would be nice to set a default max file size when resizing.  It would auto scale down the JPG compression factor.  This should be a quick change?

**Comment by JNavas2** [comment]
I don't know of a "quick" way to do that. Resizing is only deterministic on dimensions. File size depends on complexity of the image and can only be determined by compressing the image. A file size limit would require repeated compressing until an optimal size is achieved, a time-consuming process that might not even result in success. So I doubt that it would be practical.

**Comment by mikes2nd** [comment]
I think its understood it might not be 100% perfect based on default settings. Maybe throw a warning if it doesn't get under that size.

Hmm this site does it online, simply upload the image and specify the size.... I wouldnt think its "iterating" through compression levels until it reaches the size(takes .5-20 seconds it says)? https://www.imgonline.com.ua/eng/compress-image-size.php       

There is also the possibility of using Shannon's Entropy usage to estimate without doing the actual compression? https://towardsdatascience.com/the-intuition-behind-shannons-entropy-e74820fe9800

**Comment by JNavas2** [comment]
There are faster methods than iteration, but they are still slow,
especially on large images, and when dealing with multiple images.
If it isn't fast and perfect, people will inevitably complain.

**Comment by bricelam** [comment]
## Moved to Microsoft PowerToys

All future bug fixes, enhancements, and releases of Image Resizer for Windows will be done as part of the Microsoft PowerToys project.

If this is still something you'd like to see done, please follow up on [microsoft/PowerToys](https://github.com/microsoft/PowerToys)
