### ISSUE TITLE
More control over the context menu entry "Resize pictures"

### ISSUE THREAD

**Issue by somebadhat** [bricelam/ImageResizer#139]
It would be nice it I could put it with my other image tools.

![00058 jpg at 07 07 AM](https://user-images.githubusercontent.com/18543502/61876534-b4aa9280-aeb2-11e9-9db5-99bc69155763.JPG)
![00058 jpg at 07 53 AM](https://user-images.githubusercontent.com/18543502/61875959-6052e300-aeb1-11e9-9b0d-cd08d0e2576e.JPG)

**Comment by bricelam** [comment]
## Moved to Microsoft PowerToys

All future bug fixes, enhancements, and releases of Image Resizer for Windows will be done as part of the Microsoft PowerToys project.

If this is still something you'd like to see done, please follow up on [microsoft/PowerToys](https://github.com/microsoft/PowerToys)
