### ISSUE TITLE
Original modifiation date even when resizing the original pictures?

### ISSUE THREAD

**Issue by flexiblestoic** [bricelam/ImageResizer#145]
I can't retain the original modification date when I select "Resize the original pictures"
I think that option would be very useful.

**Comment by bricelam** [comment]
![image](https://user-images.githubusercontent.com/1226749/70646586-12d6d880-1bfc-11ea-9ae1-a9cff9b6a17d.png)

**Comment by JNavas2** [comment]
With respect, that doesn't really address the issue of just retaining the original date when the original image is replaced.

When a copy is created, then I think it makes sense to use the date the copy is created, but when the original is resized, I'd like to keep the original date.

As it is now, I have to remember to manually change the Advanced option each time.

**Comment by flexiblestoic** [comment]
I selected "use original date modified". However, The modified date of the new image is still updated to the moment the image is resized and doesn't keep the initial modification date. 

"use original date modified" seems to be broken for my configuration when "resize the original picture" is selected.

I am on Windows 10

**Comment by JNavas2** [comment]
Are you sure?
Works here on Windows 8.1.

**Comment by flexiblestoic** [comment]
**Before resizing**
![Capture1](https://user-images.githubusercontent.com/47722729/70651829-da61e980-1c51-11ea-8adc-e3f79246dfe1.PNG)

**Settings**
![Capture2](https://user-images.githubusercontent.com/47722729/70651839-de8e0700-1c51-11ea-9210-ae43d0693ac9.PNG)

**After resizing**
![Capture3](https://user-images.githubusercontent.com/47722729/70651844-e0f06100-1c51-11ea-938b-61d8f0f910c9.PNG)

![Capture4](https://user-images.githubusercontent.com/47722729/70651852-e483e800-1c51-11ea-9fb9-82b7b65d4651.PNG)

**Comment by bricelam** [comment]
I can't repro this either. It's working for me on Windows 10. Are you using the latest version? 3.1.1?

**Comment by flexiblestoic** [comment]
I couldn't reproduce the issue today either. Sorry, must be an oddity...
