### ISSUE TITLE
v3.1.2 download and install issues

### ISSUE THREAD

**Issue by JNavas2** [bricelam/ImageResizer#147]
1. Download blocked by Chrome, had to manually Keep.<img width="514" alt="Capture1" src="https://user-images.githubusercontent.com/14850792/71384948-3c4b1900-2599-11ea-957b-91e06640dff1.PNG">
(Screen capture is from a 2nd download just for the capture.)
2. Install blocked by Windows 8.1 SmartScreen, had to bypass to install.
3. Install offered to close and restart Windows Explorer (twice), did close it, but then failed to restart it, had to manually restart it from Task Manager.

**Comment by bricelam** [comment]
This is normal. Unless you pay a lot of money, it takes a while for installers to establish trust with the Microsoft's SmartScreen service. Basically, enough people need to click through the buried "just let me install it" option before it concedes that it's not dangerous.

**Comment by bricelam** [comment]
I paid $25 for my signing certificate. For $400 I can, "immediately establish reputation with SmartScreen". Should we really trust people more just because they have more money? 🤷🏻‍♂️

**Comment by bricelam** [comment]
The Windows Explorer issue is in [wixtoolset/wix3](https://github.com/wixtoolset/wix3). I think I've reported it to them previously...

**Comment by JNavas2** [comment]
I think you should warn users, explain, and advise them what to do.
Otherwise, less expert users will tend to be put off.
The Explorer issue is pretty serious. It cost me work in progress.

**Comment by neilh10** [comment]
I really appreciate the image Resizer and work that goes into it, and for getting the basic signing certificate. Its complex to get software that can maintain a reputation and not be used for nefarious purposes.  Thankyou.

**Comment by needfulthing** [comment]
This is the first program I tried to download and getting a complete refusal from Chrome. Are you sure there isn't a way to fix this? If Google didn't change their security feature I doubt this is only a matter of certificates, because this never stopped me from downloading a program - Chrome then just gives me a warning and I can say "Download anyway" which was not possible here.

**Comment by manbatGit** [comment]
Has done it to me a couple of times on different downloads this month... Used Firefox to complete download.

**Comment by bricelam** [comment]
Looks like 13,969 people have successfully downloaded it. Just keep clicking "keep", "more info", and "run anyway" (after verifying that it's signed by me)

**Comment by bricelam** [comment]
## Moved to Microsoft PowerToys

All future bug fixes, enhancements, and releases of Image Resizer for Windows will be done as part of the Microsoft PowerToys project.

If this is still something you'd like to see done, please follow up on [microsoft/PowerToys](https://github.com/microsoft/PowerToys)
