### ISSUE TITLE
Request: remove EXIF data

### ISSUE THREAD

**Issue by PermaPain** [bricelam/ImageResizer#149]
dear Brice Lam,

thank you for making this great piece of software. 
I'd love to have the ability (checkbox) to remove EXIF data as well, as I typically remove EXIF and resize to post online.

many thanks
cheers

edit: just saw it's been requested 4 years ago.. Where's this at? Would love this feature.

**Comment by JNavas2** [comment]
Duplicate of #3

**Comment by PermaPain** [comment]
right it's a duplicate issue.

I'm new to github, and I see #3 as locked (and certainly, I don't have any permission to postin or view that thread.)
