### ISSUE TITLE
Reorder default sizes

### ISSUE THREAD

**Issue by bricelam** [bricelam/ImageResizer#15]
Reordering the default sizes should be enabled. Ideally, you should be able to drag-and-drop them in the **Advanced options**.

**Comment by mvs12** [comment]
This wasn't ever implemented, right? It would be nice, though I imagine it isn't a priority.

**Comment by bricelam** [comment]
## Moved to Microsoft PowerToys

All future bug fixes, enhancements, and releases of Image Resizer for Windows will be done as part of the Microsoft PowerToys project.

If this is still something you'd like to see done, please follow up on [microsoft/PowerToys](https://github.com/microsoft/PowerToys)
