### ISSUE TITLE
All JPG file size -1mb.

### ISSUE THREAD

**Issue by epson950** [bricelam/ImageResizer#150]
I take pictures from my smartphone camera, the source files from the camera are about 5 mb. But when I reduce them with this program they become about 1 mb. At the same time, no matter what size I choose - for a phone 320x569 or large 1920x1080, the quality of JPEG I choose 40 or 80 - everywhere the file size is about 1 mb. It 's a big problem :( How do you solve this?

**Comment by JNavas2** [comment]
Samples would be helpful, both before and after.

**Comment by epson950** [comment]
Mi9SE 4,05mb
![IMG_20200225_183628](https://user-images.githubusercontent.com/11770015/75262735-0119d000-57fe-11ea-8df8-f27043371d3a.jpg)
Large 965 kb
![IMG_20200225_183628 (Большой)](https://user-images.githubusercontent.com/11770015/75262975-5d7cef80-57fe-11ea-826c-600ee5b4d1f9.jpg)
Phone 889kb
![IMG_20200225_183628 (Телефон)](https://user-images.githubusercontent.com/11770015/75263046-784f6400-57fe-11ea-915f-c8099a0287c4.jpg)
Advanced options > Encoding, what JPEG quality level is  set to 40 :(

**Comment by epson950** [comment]
Ver 3.1.2

**Comment by JNavas2** [comment]
In Advanced options > Encoding, what JPEG quality level is set?
Mine is set to 90. I get similar sizes, but at much higher quality.
Phone: 904 KB
Large: 1.09 MB
See Issue #80 for more on quality and size.

**Comment by epson950** [comment]
I tried Set JPEG quality level from 40 to 90- file size in my program about 1 mb. I wrote that there was a problem with any settings.
I tried the XnView Shell Extension program - it has no such problems, it makes adequate file sizes. But I like her less.

**Comment by JNavas2** [comment]
@epson950 
Then I fear you've run up against the limit of what Image Resizer can do by default.
You may be able to get smaller file sizes by installing and selecting a different codec.
Otherwise you'll have to use a different tool, depending on your version of Windows.

p.s. Apology—I thought you meant output quality was different from what you set.

**Comment by epson950** [comment]
I like your program. I would like to use it further. Even this size of file is not the biggest problem. But is it possible to change the JPEG compression codec? I can 't understand why changes in the size of my photo in any program other than this one is decreasing much more?

**Comment by JNavas2** [comment]
@epson950 
It's not mine. I'm just a fellow user trying to help.
This program is just a wrapper on Windows codecs,
and is therefore limited to the behavior of those codecs.
Other programs usually have their own codecs.

**Comment by bricelam** [comment]
The JPEG codec built into Windows isn't exactly state-of-the-art. If absolute minimal file size is your goal, you might want to try something like [JPEGmini](https://www.jpegmini.com/) or one of [its alternatives](https://alternativeto.net/software/jpegmini/).

**Comment by epson950** [comment]
I 'm sorry, but I don 't quite understand! Would you like to change the JPEG codec build into Windows? But I don 't know how to do it. I tried installing JPEGmini, but the files in your program remained large. Am I doing something wrong, or is this program replacing yours rather than adding it? I need your program, but compress JPEG more.

**Comment by bricelam** [comment]
To clarify: Image Resizer uses the built-in JPEG codec. As far as I know there is no way to change that. Instead of using Image Resizer, try an alternative that uses a more sophisticated codec.

**Comment by bricelam** [comment]
In other words, Image Resizer is primarily designed for bulk resizing images, not minimizing file size.

**Comment by epson950** [comment]
I understand. But why is the 320 * 569 file the same size as the 1920 * 1080? Equally 1 MB? And 1mb is very big for JPEG!
Also tried to install in PNG or GIF settings, but they don 't work? JPEG is recorded all the time!

**Comment by bricelam** [comment]
Weird. I wonder if there's a giant blob of EXIF metadata in there or something (#3 would help if this is the case)

**Comment by epson950** [comment]
The offer is interesting, but counter-question - why can 't you delete it in your software in settings? Or will you have to check it with your hands with a photo on your smartphone? Or I again do not correctly understand the translation: (

**Comment by epson950** [comment]
Joke. Come to the Chinese car service, please fix my car. Chinese talk pay, I 'll fix it!
Came to the Russian car service. Russian talk - pour a glass of vodka, I will fix!
Came to an American car service. The American says throw out this old wreck, buy a Chevrolet Corvette and roll!

**Comment by JNavas2** [comment]
@bricelam 
> Weird. I wonder if there's a giant blob of EXIF metadata in there or something (#3 would help if this is the case)

Good guess. Removing all metadata from @epson950 output images with [exiftool](https://exiftool.org/):
```
02/26/2020  15:41           248,216 original (Large) - Copy.jpg
02/25/2020  07:53         1,150,658 original (Large) - Copy.jpg_original
02/26/2020  15:41            24,187 original (Phone) - Copy.jpg
02/25/2020  07:53           926,629 original (Phone) - Copy.jpg_original
```
I'd call it undesired behavior at best if not an outright bug.

**Comment by epson950** [comment]
Correct assumption. But how do you decide that? Do you want to change the camera settings in your smartphone? Then you won 't get EXIF if you need to. To use other program? Bad decision. Or ask the author to add this setting to this program? It would be magnificent!

**Comment by JNavas2** [comment]
@epson950 
A quick check with exiftool suggests your phone manufacturer (Xiaomi)
is dumping a lot of junk into the image file:
```
---- ExifTool ----
ExifTool Version Number         : 11.89
Warning                         : [minor] Unknown APP4 'QTI Debug Metadata' segment
Warning                         : [minor] Unknown APP4 'QTI Debug Metadata' segment
Warning                         : [minor] Unknown APP4 'QTI Debug Metadata' segment
Warning                         : [minor] Unknown APP4 'QTI Debug Metadata' segment
Warning                         : [minor] Unknown APP4 'QTI Debug Metadata' segment
Warning                         : [minor] Unknown APP4 'QTI Debug Metadata' segment
Warning                         : [minor] Unknown APP4 'QTI Debug Metadata' segment
Warning                         : [minor] Unknown APP4 'QTI Debug Metadata' segment
Warning                         : [minor] Unknown APP4 'QTI Debug Metadata' segment
Warning                         : [minor] Unknown APP4 'QTI Debug Metadata' segment
Warning                         : [minor] Unknown APP4 'QTI Debug Metadata' segment
Warning                         : [minor] Unknown APP4 'QTI Debug Metadata' segment
Warning                         : [minor] Unknown APP4 'QTI Debug Metadata' segment
Warning                         : [minor] Unknown APP4 'QTI Debug Metadata' segment
---- System ----
[etc]
```
The QTI module is designed for close-proximity infrared (IR) detection.
It looks like Xiaomi is dumping that IR data into the image file.
_You might want to see if you can turn that off._
It's not really an Image Resizer issue.

**Comment by epson950** [comment]
Thanks big! Maybe it 's my smartphone problem. I 'll solve the problem myself. You and the author are good!

**Comment by JNavas2** [comment]
JPEG compression is as much art as science. It takes a lot of processing and memory to get small file sizes, so most software tools (not to mention cameras) make a compromise of fast and good enough that's far short of what's possible.

Google has an open source compressor called [guetzli](https://github.com/google/guetzli/) that gets excellent compression given a lot of memory and processing time.

And there's an online tool called [Compress-Or-Die](https://compress-or-die.com/) that does as well or better.
_Without resizing_, it reduces your original image to just 441 KB! Check the quality:

![original](https://user-images.githubusercontent.com/14850792/75401035-c96e5f00-58b5-11ea-80e3-38281827bc1e.jpg)

**Comment by JNavas2** [comment]
With resizing to 800x600, file size is only 47 KB:

![original](https://user-images.githubusercontent.com/14850792/75401324-a5f7e400-58b6-11ea-8809-80b34dc8916b.jpg)

**Comment by epson950** [comment]
Thanks once again! I solved the problem - replaced the Xiaomi camera with a camera from Google! The size of the photo became 1.4mb instead of 4mb. And this program compressed the new photo to 90kb! Excellent result!

**Comment by JNavas2** [comment]
![ccb66c2920f2370ad4b1f559ee5e3e301deca005-1](https://user-images.githubusercontent.com/14850792/75402244-29b2d000-58b9-11ea-9346-0617eec9d6dd.gif)
