### ISSUE TITLE
Need to change location of user.config..where would this be set

### ISSUE THREAD

**Issue by rpelletierrefocus** [bricelam/ImageResizer#151]
Just hoping you can point me in the right direction of where this is set. Thank you so much for any assistance.

**Comment by JNavas2** [comment]
See #125 (duplicate).

**Comment by rpelletierrefocus** [comment]
No, I mean that I do not want the file in that locate, I want to change where the application stores this file.

**Comment by JNavas2** [comment]
I don't think that's currently possible.
What is your use case?

**Comment by bricelam** [comment]
## Moved to Microsoft PowerToys

All future bug fixes, enhancements, and releases of Image Resizer for Windows will be done as part of the Microsoft PowerToys project.

If this is still something you'd like to see done, please follow up on [microsoft/PowerToys](https://github.com/microsoft/PowerToys)
