### ISSUE TITLE
Software Installed, Won't appear in File Explorer

### ISSUE THREAD

**Issue by PNWClimb** [bricelam/ImageResizer#152]
Hi, I'm hoping you can help me out. I'm not super tech savvy, (i'm not incompetent either). I downloaded ImageResizer 3.1.2.  When i right click on an image in File Explorer, I do not see the function to resize. I tried restarting File Explorer a few times, did a full system restart. Uninstalled and reinstalled the software. Each time, nothing changes. What am i doing wrong? 

Thank you for thehelp!

**Comment by JNavas2** [comment]
1. Which version of Windows (Control Panel > System and Security > System)? 
2. If Windows 10, have you tried Reset ([link](https://support.microsoft.com/en-us/help/12415))?
3. What types of image files have you tried (jpeg, png, etc)? _Please attach a sample image._
4. Have you tried other versions of ImageResizer?

**Comment by PNWClimb** [comment]
1. Windows 10 for Business
2. I havent reset anything because everything is working fine. Everything is working as if i had never installed the 3.1.2 software.
3. all files are jpeg. I attached a screen grab. when i right click, there is no option to resize.
4. I've never tried ImageResizer.

 I batch resize photos ALOT for work and have always used the (right click> send to> mail recipient) route, which is tedious and slows down my outlook speed. a coworker introduced me to ImageResizer and i am trying to set it up for the first time. 

![SS 03082020](https://user-images.githubusercontent.com/61950012/76174097-6a84d180-6162-11ea-9ce6-ac8f4cc6090f.jpg)

**Comment by JNavas2** [comment]
Uninstall, then try version 2.1: [Releases](https://github.com/bricelam/ImageResizer/releases)

**Comment by mardyw** [comment]
I use ImageResizer 3.1.2  so thought id check the problem out!

I have noticed that if the image has a one-drive cloud place holder icon the right click menu resize image will not appear -- however if you double click and open that image and close -- try again you will see the right click resize image appear.
So im guessing that ImageResizer doesn't recognise the onedrive place holder is an image for some reason.
Martin

**Comment by PNWClimb** [comment]
mardyw is totally right. 

I downloaded and installed  2.1 and it presents the same issue. 

thank you for all the help friends!

**Comment by mardyw** [comment]
easiest way around this inconvenience is to right click on the folder with the images in select "always keep on this device"  resize what ever images required and when finished right click again on the relevant folder  and select " free up Space" job done

**Comment by JNavas2** [comment]
That's not a real solution, since those who do not know will have no clue.
Ideally the context menu item should appear, like other relevant context menu items,
but at the very least the issue needs to be very well documented.

**Comment by bricelam** [comment]
## Moved to Microsoft PowerToys

All future bug fixes, enhancements, and releases of Image Resizer for Windows will be done as part of the Microsoft PowerToys project.

If this is still something you'd like to see done, please follow up on [microsoft/PowerToys](https://github.com/microsoft/PowerToys)
