### ISSUE TITLE
Proposed enhancement

### ISSUE THREAD

**Issue by stewartmhome1** [bricelam/ImageResizer#153]
Is it possible to enhance this product to convert the new Apple format images (ie *.HEIC) to "jpg"

**Comment by bricelam** [comment]
## Moved to Microsoft PowerToys

All future bug fixes, enhancements, and releases of Image Resizer for Windows will be done as part of the Microsoft PowerToys project.

If this is still something you'd like to see done, please follow up on [microsoft/PowerToys](https://github.com/microsoft/PowerToys)
