### ISSUE TITLE
Custom/different filename size style.

### ISSUE THREAD

**Issue by Pitros** [bricelam/ImageResizer#16]
First of all, thanks for this great app and I'm glad you're working on it again.

Could you add a ability to choose between different filename suffix - let say not only `filename (Size).extension` but for example with underscore or dash - `filename_size.extension`. 

I'm using it for quick resize for web projects and I need to rename it everytime.

**Comment by bricelam** [comment]
Already resolved by a43c6586486e5d7e4d87866aec636a888c82bebd. I hope to get a new release out soon...

**Comment by Pitros** [comment]
That's great!

**Comment by bricelam** [comment]
![image](https://cloud.githubusercontent.com/assets/1226749/17560194/fde9f60a-5ed5-11e6-9624-a820db0dd61a.png)

Are there any other parts you might want to include? My current thinking is...

* Original filename
* Size name
* Size fit
* Size with/height
* Size unit (pixel, inch, etc.)
* Actual width/height in pixels

**Comment by Pitros** [comment]
I think units, and width/height after resize most likely will be enough. But if you would add all of those you listed, that would be more than enough for 99% users.
