### ISSUE TITLE
Author-owned Chocolatey package

### ISSUE THREAD

**Issue by AnthonyMastrean** [bricelam/ImageResizer#17]
I am the current maintainer of the [Chocolatey](https://chocolatey.org) package for this application. And it's moderately popular package!

https://chocolatey.org/packages/imageresizerapp

I am interested in transferring ownership and responsibility to the author. Author-owned packages can be given "trusted" status, which helps them move through moderation very quickly (in some cases, automatically).

I can transition a standalone repository containing just this package and instructions, like this one:

https://github.com/NickeManarin/ScreenToGif-Chocolatey

The package currently lives in my personal package repository:

https://github.com/AnthonyMastrean/chocolateypackages/tree/master/packages/imageresizer

**Comment by bricelam** [comment]
Is it low-maintenance? In other words, is Chocolatey good about maintaining backwards compatibility with packages? I know they were planning to do a huge rewrite...

Regardless, I'd be happy to own it. :stuck_out_tongue_winking_eye: (I just want to know what I'm getting myself into.)

You can send a PR to this repo. Stuff it under `setup\Chocolatey`. I'll take care updating the build to package it.

**Comment by bricelam** [comment]
> Stuff it under `setup\Chocolatey`.

Ah, Chocolatey does not work that way. I've created [bricelam/ImageResizer-Chocolatey](https://github.com/bricelam/ImageResizer-Chocolatey) for you to send a PR to.

**Comment by AnthonyMastrean** [comment]
Chocolatey is fast approaching 1.0 and has been very conscious of breaking changes from early on. How much effort is required for a stable package? Very little. If you're not changing the underlying installer technology, you just update the:

 * Version
 * URL
 * Checksum

These can all be automated with the right tooling. Although, that tooling has been _very_ difficult to use. But, it's also getting some updates soon.

**Comment by AnthonyMastrean** [comment]
I'll send that PR! Please head over to Chocolatey.org and get a user account and setup your API key for the `choco push` command line.

**Comment by bricelam** [comment]
User Account: [bricelam](https://chocolatey.org/profiles/bricelam)
API Key: JUSTKIDD-ING0-0000-0000-000000000000

**Comment by AnthonyMastrean** [comment]
Ok, you're a maintainer now! I'll remove myself once this update gets through moderation. That update just contains the latest github URLs. I had to sneak the 4802 in the version to differentiate it from the 3.0 that was pushed with CodePlex URLs.

When 3.1.0 is ready, update the URLs in the `nuspec`, publish it and mention that you're the author/owner and ask for "trusted" status.

I'm also a moderator, so I can get in there and do that.
