### ISSUE TITLE
Cannot install on Windows 10 64bit?!

### ISSUE THREAD

**Issue by crazyserb** [bricelam/ImageResizer#22]
This worked just fine on previous Windows 8, but now on Windows 10 I cannot install this at all.

See attached error logs that the app comes up with. It's all gibberish to me, but it might make sense to you...

[Image_Resizer_for_Windows_20160929140013.txt](https://github.com/bricelam/ImageResizer/files/501373/Image_Resizer_for_Windows_20160929140013.txt)
[Image_Resizer_for_Windows_20160929140013_0_ImageResizer64.txt](https://github.com/bricelam/ImageResizer/files/501372/Image_Resizer_for_Windows_20160929140013_0_ImageResizer64.txt)

**Comment by bricelam** [comment]
> WixCreateInternetShortcuts:  Error 0x80004005: failed to save shortcut 'C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Image Resizer for Windows\Documentation.url'

**Comment by bricelam** [comment]
Is this fixed in [version 3.1.0-beta1](https://github.com/bricelam/ImageResizer/releases/tag/v3.1.0-beta1)?
