### ISSUE TITLE
files deleted - temporary files location?

### ISSUE THREAD

**Issue by kyussqotsa** [bricelam/ImageResizer#28]
greetings, had a bunch of photos on an SD inside my camera (sony cybershot dscw730). mounted as a USB storage device, selected the photos in the DCIM folder, selected resize, and the image resizer for windows (to medium size) was part way along its progress bar when the app closed down, and all of the photos were deleted. 

can you please advise where any temporary files are kept for this program, whether this is a known bug etc.

many thanks,
qotsa

**Comment by bricelam** [comment]
Any files removed by Image Resizer will end up in the Recycle Bin.
