### ISSUE TITLE
Suggestion: Create new folder option on Advanced Settings

### ISSUE THREAD

**Issue by Luc45** [bricelam/ImageResizer#31]
It would be nice to have an option to move resized pictures to a subfolder. "Small" subfolder, for example.

If the folder doesn't exists, creates one.

[  ] Move resized images to subfolder? [______________]

**Comment by JNavas2** [comment]
> It would be nice to have an option to move resized pictures to a subfolder. "Small" subfolder, for example.
> If the folder doesn't exists, creates one.
Seems to me that would add complexity without much real benefit
because it's so easy to select resized images by name,
and resulting issues aren't visible when resulting images are in a subfolder.

**Comment by Luc45** [comment]
> 
Seems to me that would add complexity without much real benefit
because it's so easy to select resized images by name,
and resulting issues aren't visible when resulting images are in a subfolder.
> 
Hmm, it's not that easy, I have to select them manually:
![explorer_2017-01-04_18-19-45](https://cloud.githubusercontent.com/assets/9341686/21657673/800c96ea-d2aa-11e6-9ae0-1f46be50f3d2.png)

How would you select between original, small and medium images on this folder with ease?

For me, to have the option to organize it like this, would be better:
![explorer_2017-01-04_18-23-36](https://cloud.githubusercontent.com/assets/9341686/21657777/fc6a658c-d2aa-11e6-9478-e6a12299081b.png)

**Comment by JNavas2** [comment]
Type _medium_ or _small_ in search box (upper right corner).

**Comment by Luc45** [comment]
> Type medium or small in search box (upper right corner).

Good idea, thanks!

**Comment by bricelam** [comment]
Did you know you can right-click-and-drag the images into a specific folder to get this option?
![image](https://cloud.githubusercontent.com/assets/1226749/21688017/29e188b8-d320-11e6-800b-e2c7fb423cc8.png)
The resized pictures will be placed in the target folder.

**Comment by bricelam** [comment]
Closing as won't fix. There is very little value in adding additional UI for this.

**Comment by slootzky** [comment]
I want to bring this issue back if I may.
I think the logic in file path should be create if not exists...
meaning, if user will put a path that doesn't exists, it'll just be created.
for example if file path is `resized\%1` and `resized` doesn't exists, the folder will just be created.

**Comment by JNavas2** [comment]
@slootzky 
Did you real the entire thread?
Please explain why these options don't work for you.

**Comment by bricelam** [comment]
Feel free to submit a PR.
