### ISSUE TITLE
Add a context menu icon

### ISSUE THREAD

**Issue by Rincemac** [bricelam/ImageResizer#32]
Hello everyone,

to make it short - I've just unsuccessfully searched for a way to simply **add an icon to the right-click context menu entry** in Win 10 for ImageResizer. I think it would be way easier to locate the entry that way.

I know you can add icons to custom context app links (I create myself for example), but the implementation here seems to be beyond my - let's call it scrutiny.

I simply couldn't locate any fitting shell extension entries in registry, so cannot simply add an icon link in there it seems?

Of course I'm happy for additional pointers to add an icon on my own with Win 10 (regedit etc) means.

Thought to raise it here - it's not a major "issue" per say, but maybe it's easy to implement for the future "nice to have" features.

Thanks for creating the app - made my life a lot easier a lot of times already.

**Comment by JNavas2** [comment]
I'm _not_ a fan of context menu icons --
they slow performance and I think they clutter the context menu --
so I would be against this unless it's an optional feature.

To hack it for yourself, see [How to Add Icon to Right-Click Menu in Windows 7 and higher](http://www.winhelponline.com/blog/add-icon-to-right-click-menu-windows-7/)

**Comment by bricelam** [comment]
From the [official guidelines](https://msdn.microsoft.com/en-us/library/windows/desktop/dn742392(v=vs.85).aspx):

> **Consider providing menu item icons for:**
>    - The most commonly used menu items.
>    - Menu items whose icon is standard and well known.
>    - Menu items whose icon well illustrates what the command does.
>
> **If you use icons, don't feel obligated to provide them for all menu items.** Cryptic icons aren't helpful, create visual clutter, and prevent users from focusing on the important menu items.

When I've considered it in the past, I've always felt that this utility is not one of the most commonly used, and adding an icon would just create visual clutter.

**Comment by bricelam** [comment]
Closing as *won't fix* for now, but I'd love to hear more opinions on this.
