### ISSUE TITLE
Immediate crash of v3 in Windows 7

### ISSUE THREAD

**Issue by diracsbracket** [bricelam/ImageResizer#33]
Hi,
I just installed v3.0 and tried to use it.
Whenever I press the Reisize button, it immediately crashes with the
message Image resizer has stopped working...

Also, why does it takes such a long time before the Resizer's dialog window appears, after starting the tool from the Explorer context menu? I think this was the case for all version, and still is, which I do not understand.

**Comment by diracsbracket** [comment]
I just found out that there is a [v3.1 beta version](https://github.com/bricelam/ImageResizer/releases/tag/v3.1.0-beta1). Tried that one, and it works.
Thanks!

**Comment by JNavas2** [comment]
>  diracsbracket commented:
Also, why does it takes such a long time before the Resizer's dialog window appears, after starting the tool from the Explorer context menu? I think this was the case for all version, and still is, which I do not understand.

Takes less than a second to launch on my ThinkPad running Windows 8.1 x64.
Perhaps you have some sort of system problem.
