### ISSUE TITLE
Immediate Crash of v3.0 on Windows 7 after clicking the Resize button

### ISSUE THREAD

**Issue by diracsbracket** [bricelam/ImageResizer#34]
v3.0 immedately crashes on my Windows 7 installation 
when clicking the Resize button, with the message:
Image Resizer has stopped working...

Tried uninstalling it, then build it from source. The installer does not build, because it says it is incompatible with my version of Visual Studio, which is 2015 Community. The DLL and exe build correctly though, and can be run, but only in the Debug version. The Release version crashes as well.

Then, from another issue post here, I found out there is a v3.1 beta, which I installed, and seemed to work, but that was too quick a conclusion: It worked only because the dll from my VS build was still loaded. Once that one was removed, and I uninstalled/reinstalled everything, v3.1 did not even add the Resize Image option in the context menu, neither did v3.0 after that.

Update: I decided to rebuild it from source. See my message below.

**Comment by diracsbracket** [comment]
What I did was to rebuild it on my machine from the v3.0 source.
Having never used Cake and Wix Toolset before, it was a nice new thing to "learn".

For those who want to do the same and who like me are just casual programmers:
1. Open Visual Studio 2015.
2. Go to Tools and Extensions. 
3. In the left pane of the dialog, select Online
4. In the search box on the right, just enter cake and select Cake for Visual Studio in list of results.
   Click Install.
5. Then, search for Wix, and select Wix Toolset. Select Install: this will just redirect you to the download page on the WixToolset site. Download the binary and execute it to install. Your VS2015 installation will know about it when you restart it.
6. With these 2 extensions installed, open the VS solution file of the image resizer source., then set the build type to Release and launch the build by Build | Rebuild Solution.

The (bundled!) installer can be found as:
ImageResizer-develop\setup\Bundle\bin\Release\ImageResizerSetup.exe

It works now on my Windows 7 PC!

Thanks again for this providing this Brice.

**Comment by bricelam** [comment]
So you're saying this is fixed in the latest codebase ([v3.1.0-beta1](https://github.com/bricelam/ImageResizer/releases/tag/v3.1.0-beta1))?

**Comment by bricelam** [comment]
P.S. You shouldn't need to install Cake for Visual Studio. It's only used when building form `build.cmd`.
