### ISSUE TITLE
Cancel button makes explorer crash (Windows 10)

### ISSUE THREAD

**Issue by starnutoditopo** [bricelam/ImageResizer#35]
Clicking the "Cancel" button makes Windows Explorer to hang or crash.
No way to resume it unless killing the process.

**Comment by JNavas2** [comment]
> starnutoditopo commented:
Clicking the "Cancel" button makes Windows Explorer to hang or crash.
No way to resume it unless killing the process.

Which version of Image Resizer?
Have you tried 3.1 beta?

**Comment by starnutoditopo** [comment]
Sorry for missing the version. It is the setup for rev 3.0.

**Comment by starnutoditopo** [comment]
Checked rev 3.1.0 beta 1: problem does NOT arise any more!

thanks!

On Tue, Feb 21, 2017 at 12:07 PM, Starnuto di topo <starnutoditopo@gmail.com
