### ISSUE TITLE
Some Italian translations are a bit weird

### ISSUE THREAD

**Issue by starnutoditopo** [bricelam/ImageResizer#36]
I had a quick look at Resources.it.resx  and some translation sound a bit strange.
I would suggest to change
"dimensione" for "size", instead of "misura"
"dimensioni" for "sizes", instead of "misure"  (e.g. in Advanced_Sizes)

"Il valore deve essere compreso tra '{0}' e '{1}'.",  instead of "Il valore deve essere tra '{0}' e '{1}'."

**Comment by bricelam** [comment]
The translations are crowd-sourced please feel free to contribute at https://poeditor.com/join/project/fqkB4t3mez

**Comment by starnutoditopo** [comment]
Done.

Hope to have given a useful contribution.

cheers,
  Xc
