### ISSUE TITLE
Disable ignore orientation when Fit unselected

### ISSUE THREAD

**Issue by Kbird666** [bricelam/ImageResizer#38]
thought I should start a new thread instead of adding to the Beta Thread....

I installed the Beta as the Resizer is not calculating the resize here correctly , it was not in Ver.3 and is not with the Beta either , and the new Fill and Fit Option in the new Beta don't help with getting the true size. 

For eg. my Main monitor is a BenQ BL3200 @ 2560x1440  and if I do a Custom Resize to that size  , I get 1080x1440 with the Beta if I set Fill or Stretch instead of Fit I get 1440x1440
 
Like most I am on Windows 10 these days Version 1607.

**Comment by JNavas2** [comment]
Beta works fine here on Win 8.1 x64 (1800x1200 image resized to 2160x1440).
Are you **sure** you don't have _Make pictures smaller but not larger_ checked?
p.s. FYI, Windows 7 is still far ahead of Windows 10.

**Comment by Kbird666** [comment]
I am resizing down, not sure if that is the difference?,  currently my Phone (Nexus 6P)  is set so it take 4032x3024  (4x3aspect - 12.2 meg-max) images so depending on if I am storing an image, emailing it to a Client or Posting it , I usually resize the the higher res image down to something smaller. Maybe the phone is doing something weird to the Files that Resizer is not understanding?

This after noon I also tried 1920 x 1080 and got 810 x 1920 images  so I reinstalled a copy of 2.1 I still had and it is doing the same thing.  I never noticed this before as I had ToolTips off in the past but now hovering over an image it tell me the size, etc.  I didn't believe it so I have opened images in a number of different image applications now and the tell me the same thing.

Yes it has taken a bit to get used to Win10 ...and I still was happier with Win7 like you :)

**Comment by JNavas2** [comment]
Generated sample 4032x3024 image, used Beta with Custom Fit setting 2560x1440,
and resulting image is 1920x1440, as expected. See: http://i.imgur.com/X0ExIpY.png
Repeated the test with a full resolution image from my Nexus 5X,
and it also worked as expected. Images: http://imgur.com/a/bkKkW
Why don't you resize on your phone with Google Snapseed?
I prefer and use Win 8.1 Pro x64. I would never use Win 10.

**Comment by bricelam** [comment]
> I prefer and use Win 8.1 Pro x64. I would never use Win 10.

I am incredibly disturbed by this statement. 😏 But, to each his own...

**Comment by Kbird666** [comment]
Getting used to Win 10 , win7 is still there "under the hood" once you learn where to look , though i still fear an onslaught of Advertising in the future. Never had Win 8 so can't Comment.

I am surprised Brice that was your only comment though.....  no ideas why this might be happening to me ? since apparently JNavas2 is having the same issue , his converted images of 2560x1440 images are coming out at 1920x1440 which is actually what happens if I use the Office Picture Manager from Office 2007.

Thanks JNavas2 but your own comment tells me it is not working correctly there either, (2560px coming out at 1920px is not correct) . I had not heard of Google Snapseed (new to Android , had to give up my trusty Samsung Focus finally :) ) I will have a look thanks....

**Comment by JNavas2** [comment]
> since apparently JNavas2 is having the same issue , his converted images of 2560x1440 images are coming out at 1920x1440 which is actually what happens if I use the Office Picture Manager from Office 2007.

1920x1440 is actually _correct_, since 2560x1440 is the _bounding box_ for my resize, and 1920x1440 is the largest 4:3 image that will Fit in that bounding box.
If you want it wider to fit your 16:9 monitor, use Fill instead of Fit.
See this video capture: https://youtu.be/TvtdbiOIFLY

**Comment by Kbird666** [comment]
Thanks for the video John , can you explain the "bounding box" or link me to more info perhaps?  (a google search just has thousands of pages with that reference.)

I did try Fill and Stretch (see the 1st post) and I get 1440x1440 (4x4 aspect) instead of 1080x1440 with them

KB

**Comment by JNavas2** [comment]
> my Main monitor is a BenQ BL3200 @ 2560x1440 and if I do a Custom Resize to that size , I get 1080x1440 with the Beta if I set Fill or Stretch instead of Fit I get 1440x1440

A Custom size of 2560x1440 means the max horizontal is 2560 and the max vertical is 1440, so if you resize a 4032x3024 _landscape mode_ image with Fit, you'll get 1920x1440, because a 2560 horizontal would mean 1920 vertical, and that would violate the vertical of the 2560x1440 _bounding box_. You'll only get 2560x1440 with Fill, which resizes and crops.

Please attach (1) your original image and (2) a screenshot of ImageResize just before you click Resize (like this).
![img original](https://cloud.githubusercontent.com/assets/14850792/25368204/afef47d2-292f-11e7-92a3-eafa6d29be24.jpg)
![screenshot](https://cloud.githubusercontent.com/assets/14850792/25368210/b84b7efa-292f-11e7-8b3e-51f7aebdff38.png)

**Comment by JNavas2** [comment]
Your comment on my video https://youtu.be/TvtdbiOIFLY
> Thanks John , I'm not sure why it's not working like that for me , I get either 1080 (2560) with fit or 1440(2560) with Fill﻿

Are you doing it _exactly_ as in my video (and in the screenshot above)?
In resolution, 1st number is horizontal, 2nd number is vertical, 
Horizontal greater than vertical is _landscape mode_ (wider than tall), like your monitor.
Horizontal smaller than vertical is _portrait mode_ (taller than wide).
Is your original image portrait mode? Did you check _ignore orientation_?

**Comment by JNavas2** [comment]
Video simulation: https://youtu.be/v3d24G5pjec
Red box is Custom 2560x1440 (16:9) setting in Image Resizer.
Blue rectangle is 4:3 image to be resized.
Mode is Fit.
Part 1 has the image in _landscape mode_. Note how it has to fit inside the _bounding box_.
Part 2 has the image in _portrait mode_. Note how it has to fit inside the _bounding box_.
And note how the result is different.

**Comment by Kbird666** [comment]
HI thanks John , I appreciate the time you've taken tonight , I will try your suggestions in the Morning but I am getting the feeling I will need to be more careful on whether the image is in Landscape Mode or Portrait Mode and should likely switch my Phone to a 16x9 aspect ratio too. I was assuming that the Resizer automatically took the longest measurement as the 1st measurement and the orientation did not matter with the Ignore box checked.

One good thing about the Beta is that you can make your own custom resize options , so I guess I will make one for Landscape and one for Portrait and try it out.

Thanks again.

KB

**Comment by JNavas2** [comment]
I think (but don't know for sure) that _Ignore the orientation of pictures_ option
refers to the EXIF Orientation value. For more information, see
http://www.impulseadventure.com/photo/exif-orientation.html

**Comment by bricelam** [comment]
> Ignore the orientation of pictures option refers to the EXIF Orientation value.

No. Right now, **Ignore the orientation of pictures option** means to swap the specified dimensions to match the orientation of the photo before resizing. This gets a little wonky with the **Fill** and **Stretch** options, and I've considered unchecking and disabling that option when using them.

**Comment by Kbird666** [comment]
Thanks john I have a much better idea of what is going on now  , and from Brice's post above it seems my assumption of it switching measurements was correct but I was making the mistake of not turning it off when not needed , though I don't remember having to do that in the earlier versions to get things right  (or i never noticed the issue )  I always left it on so I didn't need to worry about Landscape or Portrait Modes , so I likely have a bunch of photos stored with weird sizings ...nothing important fortunately.

I have made Custom Portrait modes for each size and set ALL profiles to Fill (fit still has bounding box issues for me) and it now seems to be working properly here , so once again thanks for your help , I was pretty sure the issue was on my end  :)  since I couldn't find any other comments on the problem though I think it would be an easy mistake to make for anyone not having a good knowledge of image manipulation .

**Comment by JNavas2** [comment]
@Kbird666 
Good to hear. Better documentation is (always) needed.

**Comment by Kbird666** [comment]
There's documentation?  missed that too...

**Comment by JNavas2** [comment]
http://www.bricelam.net/ImageResizer/

**Comment by Kbird666** [comment]
Ok , I do know that single page webpage , its how I got here after I noticed my issue .  I guess it is suppose to be simple enough that "Documentation" is not needed.... 

Glad you were here John helping out as I would not of figured it out otherwise without many hours using my GoogleFu :) I am sure.

KB

**Comment by JNavas2** [comment]
Thank you. What's simple and obvious to one person can be confusing and misleading to someone else. Case in point is the _Ignore the orientation of pictures_ option, which fooled me. So good documentation is always important. If Brice setup a wiki (hint), we could help. In the meantime I give back by trying to help here.

**Comment by bricelam** [comment]
The documentation should go on http://bricelam.net/ImageResizer. It's open source too; you can send a PR to the [gh-pages](https://github.com/bricelam/ImageResizer/tree/gh-pages) branch.

**Comment by bricelam** [comment]
It uses [Jekyll](http://jekyllrb.com) to generate the HTML from [Markdown](https://guides.github.com/features/mastering-markdown/). If you want to test it locally, here are instruction on [setting it up locally](https://help.github.com/articles/setting-up-your-github-pages-site-locally-with-jekyll/).

**Comment by JNavas2** [comment]
No offense intended, but _ugh_.

**Comment by bricelam** [comment]
lol, feel free to email me a Word document (or similar) and I'd be happy convert it.

**Comment by JNavas2** [comment]
_"If the only tool you have is a hammer, you will see every problem as a nail."_ ;)

I think you need to rethink and clarify what you mean by "orientation".
As my earlier answer illustrates, the EXIF Orientation flag is increasingly
common as more and more devices incorporate orientation sensors.
And I don't think just disabling the option for Fill and Stretch really addresses all the issues.
What you apparently intend is for the option to reverse settings if needed to match
image orientation, and that can be useful for Fill and Stretch as well as for Fit
_if_ that functionality is properly communicated and understood,
perhaps by changing the wording to something like
"Adjust settings orientation to image orientation",
including the role (if any) of the EXIF Orientation setting.
There's also the issue of filename Width and Height parameters,
which can be confusing and misleading when settings are reversed.
It might make for less confusion to have them reflect the _actual dimensions_
of the output image instead of the settings (which might be reversed).

**Comment by Kbird666** [comment]
" Ugh " is one word for it  :)  , Brice you are forgetting that we are all not Programmers or perhaps familiar with GitHub and how it works , ie what is a PR?....  don't worry I don't need to know really, as I won't be using it either.. just an illustration...

I see the thread name got changed but it is not clear enough ...if I choose Custom>Fit>2560x1440 and uncheck Ignore , I still get an incorrectly sizes images ...due to the bound box issue ... of 1920x1440  from a 4032x3024 (4x3) image doing it from a 3820x2160 (16x9) image it works fine.

Please don't disable Fill and stretch if that is what you are thinking please, I have made a Portrait and Landscape Mode for each size and set them all to Fill and it seems they all work as they should as long as you choose the correct Orientation on resize.

And I agree with John's Post above , some good thoughts there.

And I just wanted to say Thanks For the App/Addon too Brice

**Comment by JNavas2** [comment]
> And I just wanted to say Thanks For the App/Addon too Brice

Me too!

**Comment by bricelam** [comment]
My original thought on fixing this was that when you selected a size (or changed the custom size) to **Fill** or **Stretch** then **Ignore the orientation of pictures** would be unchecked, and if you selected **Fit** it would be checked. You were then free to change the setting after that.

But I'm having second thoughts. You may have landscape and portrait photos in 16:9 ratio that you want to fill 4"x6". The portrait photos should be 6" high and the landscape ones should be 6" wide.

It could also be very annoying for the checkbox to be checked and unchecked as you change something seemingly unrelated.

I think the current behavior is correct, and this issue is best solved by better documentation about what **Ignore the orientation of pictures** means.

**Comment by bricelam** [comment]
Filed #60
