### ISSUE TITLE
Error on large files - too much metadata

### ISSUE THREAD

**Issue by statler** [bricelam/ImageResizer#39]
I saw that this probably had some answers in the old codeplex site, but no longer...

Basically when resizing large files, the biggest of them will fail with a too much meatadata warning - any ideas?

Will this help?
[https://forums.asp.net/t/1917748.aspx](https://forums.asp.net/t/1917748.aspx)

**Comment by JNavas2** [comment]
Can you provide a sample image that fails?

**Comment by bricelam** [comment]
Implementing issue #3 might be one way of mitigating this error.

**Comment by JNavas2** [comment]
> Implementing issue #3 might be one way of mitigating this error.

If so, please make that an option. I sometimes need to preserve all metadata. Thank you.

**Comment by bricelam** [comment]
@JNavas2 I imagine a check box in the advanced options to strip all but the essential metadata. It would be off by default since yeah: data loss.

**Comment by bricelam** [comment]
Will attempt to address as part of #3.
