### ISSUE TITLE
MSI's of recent builds?

### ISSUE THREAD

**Issue by samuelleung83** [bricelam/ImageResizer#40]
Brice, pleased to see you are still working on this project. Are there **MSI's** of the latest stable and beta release?

**Comment by JNavas2** [comment]
https://github.com/bricelam/ImageResizer/releases

**Comment by samuelleung83** [comment]
JNavas2 Thanks for the quick response, but I can't seem to find the MSI's of the latest stable and beta release. I can only see the EXE's in the releases list.

**Comment by JNavas2** [comment]
Those EXE files are installers. Is there a reason you want MSI files instead?

**Comment by samuelleung83** [comment]
No reason in particular really. I just noticed older versions had MSI's and it's nice to have the choice of both.

**Comment by bricelam** [comment]
The MSIs embedded in the EXE are no longer self-sufficient, so it doesn't make a lot of sense to ship them separately. Use the EXE. It knows how to do the right thing based on your operating system's architecture.

**Comment by the-xlr8r** [comment]
Hi bricelam
i have been using this for years and think its a valuable tool for windows.
I too would like to obtain an .msi version. Basically, i use a program called Batchpatch to roll out software across our network, and the exe from your program doesn't have an install ID . is there any way i can get an msi version please ?
kind regards
