### ISSUE TITLE
Strong changes in coloration

### ISSUE THREAD

**Issue by slizzered** [bricelam/ImageResizer#41]
I have a picture with 591x591px (_Example images below_). I wanted to test the "make images smaller not larger" option and set the following:
- Custom size: fit 1000x1000 px
- - [x] Make pictures smaller not larger
- - [ ] Resize the original pictures
- - [x] Ignore the orientation of pictures
- JPEG Quality Level 100

I expected one of 2 things to happen:
- Creation of an identical copy (as the picture didn't require resizing) with the new name (This would be great!)
- Creation of a newly encoded copy that maybe shows some artefacts and slightly changed file size.

The latter happened (which is OK and can be expected). However, the **colors are visibly changed** now. The saturation appears reduced, maybe there was some automatic white balance. I assume this is a result of re-encoding the image. Other image resizing software didn't change the colors, so this might be due to some setting in the encoder or a bug.

**Original:**
![suite01](https://cloud.githubusercontent.com/assets/903310/25433636/5d21b728-2a89-11e7-92ce-bdfb26c06c82.jpg)
**Resized to same size:**
![suite01 custom](https://cloud.githubusercontent.com/assets/903310/25433646/69c69430-2a89-11e7-933f-f5ded566563e.jpg)

**Comment by JNavas2** [comment]
Try the beta: https://github.com/bricelam/ImageResizer/releases
It worked properly for me.
Original:
![original](https://cloud.githubusercontent.com/assets/14850792/25437516/7c2f5dfc-2a4b-11e7-94db-0296b9c162cd.jpg)
Resized:
![original 1000 x 1000](https://cloud.githubusercontent.com/assets/14850792/25437548/90d4008c-2a4b-11e7-8bb9-d28d24ec6fd9.jpg)
Difference:
![difference](https://cloud.githubusercontent.com/assets/14850792/25437554/990d6f54-2a4b-11e7-988a-58aa72600d2a.jpg)
