### ISSUE TITLE
Reimage Sizer - Pics are all black

### ISSUE THREAD

**Issue by millsam01** [bricelam/ImageResizer#44]
On a Windows 7 pc, every picture we resize  come out totally black.

Someone else can resize the same pic and it works properly.

What could be the issue?

**Comment by JNavas2** [comment]
Are you using Image Resizer beta? If not, try it:
https://github.com/bricelam/ImageResizer/releases/tag/v3.1.0-beta1
What kind of images (JPEG, PNG, etc)?
Certain types of encoding can cause problems in older viewers.
Have you tried other viewers; e.g., http://irfanview.com
Are they still black when copied to later versions of Windows?
Please upload samples before and after resizing.

**Comment by bricelam** [comment]
I'm not able to reproduce this issue, so I can't debug it. If anyone can provide more details, I'll dig into it.
