### ISSUE TITLE
Recent Win 10 update broke program

### ISSUE THREAD

**Issue by HEspoke** [bricelam/ImageResizer#46]
![image](https://user-images.githubusercontent.com/26511314/28835674-344910d6-76b4-11e7-8906-481eb394b934.png)
After my computer updated to the Creators Edition of Windows 10 recently the program just shows a white screen when I try and resize an imaage. Any help would be appreciated. Thanks

**Comment by Akxe** [comment]
Try https://github.com/bricelam/ImageResizer/releases 3.1, it fixed it for me.

**Comment by JNavas2** [comment]
Suggest:
1. Uninstall current version.
2. _Restart computer._
3. Install [3.1.0-beta1](https://github.com/bricelam/ImageResizer/releases).
4. Restart computer.

**Comment by bricelam** [comment]
I'll assume this is fixed in 3.1. Version 3.0 used some unsupported libraries, that have probably been broken by recent updates to Windows/.NET Framework.
