### ISSUE TITLE
unfreeze the UI

### ISSUE THREAD

**Issue by foxontherock** [bricelam/ImageResizer#47]
May I suggest to add some "application.doevents" in the loop to help unfreeze explorer.exe UI when we ask to resize a lot of images.

**Comment by foxontherock** [comment]
I don't think that I use the beta version, but even if the app is not directly communicating with explorer.exe, it takes 100% of cpu.  So, some "doevents" will allow all other apps, not just explorer, to continue running without freezing, I think that it may help be more "smooth"!

**Comment by bricelam** [comment]
Lol, I'd argue that a bulk image resizer that *didn't* use 100% of your CPU and Disk I/O is doing something wrong. 😉

**Comment by JNavas2** [comment]
> Lol, I'd argue that a bulk image resizer that didn't use 100% of your CPU and Disk I/O is doing something wrong. 😉

Yes. I'm not seeing any UI issue -- during a resize of 1000 images I was able to interact normally (no freezing) with the system (Windows 8.1 Pro x64 on ThinkPad T460p) including Explorer.

**Comment by foxontherock** [comment]
I had that issue with a ssd drive, so i didn't had to wait for hdd.

**Comment by JNavas2** [comment]
> I had that issue with a ssd drive, so i didn't had to wait for hdd.

I had no issue, and I have an SSD (Samsung 840 EVO 1GB).
