### ISSUE TITLE
resizing finished with errors - too many meta data changed

### ISSUE THREAD

**Issue by frameier** [bricelam/ImageResizer#48]
Hello,

Image resizer is working well for most of my .jpeg files.
But on some files, Image Resizer is quitting with the following error:

resizing finished with Errors - to many meta data changed

Image Resizer Version: 3.0.4802.35565

![imageresizer_error](https://user-images.githubusercontent.com/32056092/30532171-1c2167f0-9c53-11e7-82a8-7cbef32cdd35.JPG)

Do you have any hint how to resolve this error?

Thank you and best regards,
Karl-Heinz

**Comment by JNavas2** [comment]
Try Image Resizer beta 3.1: https://github.com/bricelam/ImageResizer/releases/tag/v3.1.0-beta1
(Uninstall the version you have now before installing the beta.)

**Comment by bricelam** [comment]
Will attempt to address as part of #3.
