### ISSUE TITLE
Fit algorithm fails if only one dimension is specified

### ISSUE THREAD

**Issue by Akxe** [bricelam/ImageResizer#49]
Version - 3.1-beta

The algorithm fails if the dimension specified is smaller than the other. 

Example image: 1000x500
resize to: fit to 100x(auto)
expected output: 100x50
actual output: 100x50

Example image: 500x1000
resize to: fit to (auto)x100
expected output: 50x100
actual output: **1x1**

**Comment by bricelam** [comment]
I get a 100x200 image in the latest codebase. Unchecking **Ignore the orientation of pictures** makes it work as expected. This relates to #38
