### ISSUE TITLE
Context menu crashes

### ISSUE THREAD

**Issue by pdlk** [bricelam/ImageResizer#52]
After trying to open context menu of image files (right click) Windows Explorer crashes, so does Total Commander. Issue remains also after the program is unistalled. Any advice how to fix context menu?

Version 3.0 (after that I've tried to install 3.1 beta 2, doesn't help)
Windows 10 latest update

**Comment by bricelam** [comment]
Try deleting these registry keys if they still exist:

* HKCR:\Directory\ShellEx\DragDropHandlers\Image Resizer
* HKCR:\*\ShellEx\ContextMenuHandlers\Image Resizer

**Comment by pdlk** [comment]
No such keys found in HKEY_CLASSES_ROOT and no string like "Image Resizer" exists in registry anymore. Any other tip?

**Comment by bricelam** [comment]
Hmm... Are either of these GUIDs anywhere to be seen?

* 09082E28-A5CA-47A7-8571-A2236C411E91
* 51B4D7E5-7568-4234-B4BB-47FB3C016A69

If not, it may be something else causing the issue.

**Comment by pdlk** [comment]
Nope :( So.. i will look for other solutions.

**Comment by JNavas2** [comment]
I suggest you look for the cause of your crashes, which would appear to be something other than Image Resizer. Start with good anti-malware and System File Checker <https://support.microsoft.com/en-us/help/929833/use-the-system-file-checker-tool-to-repair-missing-or-corrupted-system>.

**Comment by bricelam** [comment]
**CCleaner** is also good at finding bad registry keys that may be causing it.

**Comment by pdlk** [comment]
CCleaner was my first choice... but no success :( I will try to walk through the event logs to find out whats going on.

**Comment by pdlk** [comment]
Thanks guys for your ideas. In the end it was phantomPDF issue but maybe check if Image Resizer and Phantom's ConvertToPDFShellExtension module (Faulting module path: C:\Program Files (x86)\Foxit PhantomPDF\plugins\ConvertToPDFShellExtension_x64.dll, Report Id: 6522c256-c85d-428e-a890-ec63f36f91be)  have no impact on each other.
