### ISSUE TITLE
ImageResizer discards color profile

### ISSUE THREAD

**Issue by stephtr** [bricelam/ImageResizer#53]
Even though I'm using Image Resizer regularly, for me there is only one significant bug/missing feature:
When resizing images Image Resizer simply discards the embedded color profiles, which result in changed colors if the image is not in sRGB, which is a bit problematic for e.g. photographers (for example when using Adobe RGB).

**Comment by bricelam** [comment]
Can you confirm if this is still broken in [version 3.1.0-beta2](https://github.com/bricelam/ImageResizer/releases/tag/v3.1.0-beta2)?

**Comment by stephtr** [comment]
Yes, I am using 3.1.0-beta2.
Interestingly it doesn't happen using [webkit's sample pictures](https://webkit.org/blog-files/color-gamut/), but attached are two images, one in Adobe RGB and one in sRGB, which look nearly identically, but not after resizing them.
 
![adobergb](https://user-images.githubusercontent.com/5764184/34495808-1e4425c0-eff7-11e7-97be-3522d455c0ba.jpg)
![srgb](https://user-images.githubusercontent.com/5764184/34495809-1e6e2b18-eff7-11e7-880d-2f3996930d99.jpg)

**Comment by bricelam** [comment]
Awesome, thanks for the failing samples. I'll dig into it when I get a chance.

**Comment by bricelam** [comment]
Weird. By *not* copying the color profiles of the original, the colors are preserved...

**Comment by bricelam** [comment]
You can test it out on this build, and let me know if it looks better to you too: https://ci.appveyor.com/project/bricelam/imageresizer/build/1.0.29/artifacts

**Comment by stephtr** [comment]
Perfect, it looks like it's fixed!
