### ISSUE TITLE
Resizing .emf files in windows 10

### ISSUE THREAD

**Issue by adamrees89** [bricelam/ImageResizer#56]
When trying to resize a .emf file in windows 10 using this tool it tends to crash explorer on my PC.  On others PC it just fails to resize the image.

This worked on Windows 7, and this issue possibly links to #46

**Comment by JNavas2** [comment]
Not related to #46. .emf is Enhanced Windows Metafile format, which is not a pure raster (bitmap) image, should not normally require resizing since it's sized automatically to the target device. Image Resizer shouldn't crash, but I don't think it supports .emf.

**Comment by JNavas2** [comment]
Are you using the beta?
Here's what I get on Windows 8.1: 
<img width="274" alt="capture" src="https://user-images.githubusercontent.com/14850792/35445744-66f17444-0267-11e8-899b-d3b6ace6e6f4.PNG">

**Comment by bricelam** [comment]
If you have a Windows Imaging Component Decoder for *.emf files, it should be able to resize it. Since it won't be able to encode the result as an *.emf file, it will use the fallback encoder (specified in the advanced settings). The default fallback encoder is *.jpg.
