### ISSUE TITLE
Deploy through WMI?

### ISSUE THREAD

**Issue by mattharwood** [bricelam/ImageResizer#6]
Hi there,

Staff at a school I work with love Image Resizer, but they would like an easy way to deploy school-wide. Are there any parameters we can run on the installer for a remote, silent install at all please?

Thanks in advance,
Matt

**Comment by bricelam** [comment]
It's a standard [WiX](http://wixtoolset.org/) bundle. `/passive` displays minimal UI with no prompts. `/quiet` displays no UI with no prompts.
