### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by bricelam** [bricelam/ImageResizer#60]
The website should have a brief description about what each setting does.

**Comment by steveroot** [comment]
@bricelam - I'd be happy to help and write some things. If that would help please let me know how.

**Comment by bricelam** [comment]
## Moved to Microsoft PowerToys

All future bug fixes, enhancements, and releases of Image Resizer for Windows will be done as part of the Microsoft PowerToys project.

If this is still something you'd like to see done, please follow up on [microsoft/PowerToys](https://github.com/microsoft/PowerToys)
