### ISSUE TITLE
Does the setup embeds an MSI install? Conflicts here!

### ISSUE THREAD

**Issue by RixNox** [bricelam/ImageResizer#62]
I am attempting to wrap image resizer exe setup into a MSI to allow deployment over a network, however this will generate conflicts (errors).
MSI Wrapper is a free tool that can be used to achieve this. In the help section they state:

> You can experience that the installation of the MSI package hangs if your wrapped executable installer tries to install an embedded MSI packages. The Windows Installer seems to get confused if the MSI packages are nested in a way where your MSI launches an EXE that launches another MSI. Scenarios like this can happen if your executable installer contains a file like vcredist_86.exe. This is the Visual Studio C++ runtime redistribution package. Even though it looks like an executable, it is in fact an MSI package in disguise. A possible workaround to this situation could be to add a switch to your executable installer that will disable the installation of this runtime. This package can be distributed as a standalone installer in a software distribution environment.

So the question is: are you using an embedded MSI in the setup?

**Comment by bricelam** [comment]
Yes. The setup is a [WiX bundle](http://wixtoolset.org/documentation/manual/v3/bundle/) that chains the .NET Framework bootstrapper and two MSIs (one for x86 and one for x64)

**Comment by RixNox** [comment]
Could it be possible to extract the 64 bit msi installer somehow?

**Comment by xternaal** [comment]
Hi, great software thanks!
 I would also be interested in a msi for deployment.

**Comment by bricelam** [comment]
You can download [wix311-binaries.zip](https://github.com/wixtoolset/wix3/releases) and run the following:

    dark.exe ImageResizerSetup.exe -o ImageResizerSetup

The two MSIs will be under `ImageResizerSetup\AttachedContainer`. Be sure to install both MSIs on 64-bit machines.

**Comment by RixNox** [comment]
Thanks a lot!
