### ISSUE TITLE
Allow resizing by percentage

### ISSUE THREAD

**Issue by andrewducker** [bricelam/ImageResizer#63]
I'd like to be able to resize a load of photos I've taken, but doing it to half/quarter/etc current size.

**Comment by JNavas2** [comment]
Why would that be preferable to dimension? If there's much size variation, then percentage would also be problematic, no? Sounds like you may need a more complex rule than either.

**Comment by andrewducker** [comment]
Generally I prefer the quality you get when reduce things so that an exact number of pixels are turned into new ones.  So turns 4 pixels into one (by reducing size by 50% in each direction) looks better to me than some of the odd effects on straight lines when you turn 3.76 pixels into one.

**Comment by bricelam** [comment]
![image](https://user-images.githubusercontent.com/1226749/37623521-3c11ea8a-2b82-11e8-8d7f-ff50a8d74bc9.png)

...what am I missing?

**Comment by JNavas2** [comment]
@andrewducker 
> Generally I prefer the quality you get when reduce things so that an exact number of pixels are turned into new ones. So turns 4 pixels into one (by reducing size by 50% in each direction) looks better to me than some of the odd effects on straight lines when you turn 3.76 pixels into one.

Depends on resizing algorithm, as well as source resolution and quality of source image.
How about giving us a real example where IR is currently suboptimal?
And if you like, I can give you use cases where percentage reduction gives poor results.

**Comment by andrewducker** [comment]
Huh.  The UI I get is not the same as that one.  But I hadn't actually noticed that the "Scale to" had a Percent option.  So blame my observation skills - sorry!

**Comment by bricelam** [comment]
The screenshot is from [version 3.1.0-rc1](https://github.com/bricelam/ImageResizer/releases/tag/v3.1.0-rc1). Give it a try! Let me know if you find bugs. 😉
