### ISSUE TITLE
'Can't resize the following pictures' error

### ISSUE THREAD

**Issue by tigerstyle2ne1** [bricelam/ImageResizer#64]
When I am resizing photos, maybe 2/3rds will resize correctly, but others will give the error 'Can't resize the following pictures' and it lists the file names.

I've tried to fix it be uninstalling and re-installing the app, but this hasn't worked. Switching between Release version and the Beta hasn't heIped either. I noticed though that when doing a new install, it remembered my custom resize settings from the last install, so is it uninstalling fully? How can I perform a full uninstall and reset the program back to it's defaults? 

It was working great on an old laptop i was using, but when I swapped work laptops I get this error.

**Comment by bricelam** [comment]
What error message does it give underneath each filename?

**Comment by tigerstyle2ne1** [comment]
https://imgur.com/GWCK50f

**Comment by bricelam** [comment]
Try deleting any directory starting with `ImageResizer.exe` under `%LOCALAPPDATA%\Brice_Lambson`.

**Comment by tigerstyle2ne1** [comment]
That has fixed it, thank you.
