### ISSUE TITLE
Crash on load

### ISSUE THREAD

**Issue by mystinen** [bricelam/ImageResizer#66]
Used to work very well indeed, but recently crashes immediately after 'Resize pictures' is selected from the Explorer context menu. This is on Windows 7 64-bit. The issue happens with both the stable 3.0 version if ImageResizer as well as the RC version.

Following is crash details:

Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	ImageResizer.exe
  Problem Signature 02:	3.1.0.2
  Problem Signature 03:	5a95e7be
  Problem Signature 04:	PresentationCore
  Problem Signature 05:	4.7.2053.0
  Problem Signature 06:	58fa7581
  Problem Signature 07:	46a2
  Problem Signature 08:	16
  Problem Signature 09:	PSZQOADHX1U5ZAHBHOHGHLDGIY4QIXHX
  OS Version:	6.1.7601.2.1.0.256.28
  Locale ID:	2057
  Additional Information 1:	56d3
  Additional Information 2:	56d326b07bcd155580e26370c80ae313
  Additional Information 3:	019c
  Additional Information 4:	019cb06786aa4a9fa28f7305013c737f

**Comment by bricelam** [comment]
It's all gibberish to me. If you run ImageResizer.exe from a command prompt, does it give any additional information?
