### ISSUE TITLE
'Resize pictures' doesn't appear on Windows 7 contextual menu (right click on image in file explorer)

### ISSUE THREAD

**Issue by maximelebreton** [bricelam/ImageResizer#67]
Hello @bricelam,
I am looking for an application like this one for years and I just discovered it today!
Unfortunately it doesn't work on my machine. (`Windows 7 64 bits`)
I've tried `3.0` and `3.1 RC1` versions, trying to reboot my computer, but it **doesn't appear in the explorer pictures contextual menu**...

Any ideas?
I can not wait to test it!

**Comment by bricelam** [comment]
It should work. Try uninstalling everything and installing [version 3.1.0-rc1](https://github.com/bricelam/ImageResizer/releases/tag/v3.1.0-rc1) again.

**Comment by maximelebreton** [comment]
Already tried (As I said in my previous message).
But I tried it again to be sure but no, it still doesn't work...

Is there some logs somewhere to help us understand?

**Comment by panther2** [comment]
Runs fine here on Win7.64...

... sounds trivial... but have you granted admin rights (UAC prompt) when installing?

**Comment by maximelebreton** [comment]
i let you judge by this video screen (uninstall and reinstall as admin):  

![imageresizer2](https://user-images.githubusercontent.com/1072425/38086785-fb6a91f4-3355-11e8-9c47-a4b026289d6e.gif)

**Comment by panther2** [comment]
I see. On my context menu it appears between "7-zip" and "Open with":

![resizer](https://user-images.githubusercontent.com/20812775/38096300-d1bed5c8-3372-11e8-8ced-50d1506d9537.png)

**Comment by panther2** [comment]
@maximelebreton 
But in your video I miss the UAC-prompt when you run the installer as admin.

**Comment by JNavas2** [comment]
When installing Image Resizer, _right_-click the installer, then choose **Run as administrator**.

![install_ir](https://user-images.githubusercontent.com/14850792/38097664-d6829380-332a-11e8-8cff-e560ac98ee57.jpg)

**Comment by panther2** [comment]
According to his above video, @maximelebreton  did exactly that, @JNavas2 , it's just the French equivalent.

What bothers me is that the UAC did not pop up. 
Without confirmation of admin privileges by confirming the UAC no information will be written to the registry when installing. So there is no entry in the context menu.

This might be the reason.

**Comment by JNavas2** [comment]
UAC prompt doesn't appear here either (Windows 8.1 Pro 64-bit),
even with _Run as administrator_ when installing RC1. Instead:
______<img width="364" alt="capture" src="https://user-images.githubusercontent.com/14850792/38100192-8ed5c2c6-3331-11e8-842f-0e1470e85fca.PNG">
RC1 can _only_ be installed here from an _Administrator_ account,
something that should be addressed before release.

**Comment by bricelam** [comment]
Weird. The WiX bootstrapper should automatically elevate as needed. Possibly a bug on their end. I'll follow up.

**Comment by bricelam** [comment]
Are there any WiX/MSI experts out there who can help with this one?

**Comment by kdekker** [comment]
I ran into the same issue on Windows 10 (build 1609 level). Uninstalling 3.1 and moving back to 3.0 (=reinstall) made the 'Resize Pictures' context menu in the file explorer visible again. I did not recheck when moving to 3.1 neither I did check (probably bad) dependencies on the shell extension DLL. If wanted to do so, just let me know.
