### ISSUE TITLE
Allow conversion of image formats

### ISSUE THREAD

**Issue by ryanshow** [bricelam/ImageResizer#68]
I have a bunch of large TIFF originals that I'd like to convert down to JPEG thumbnails. It would be nice if I could select an image format for a preset. I guess the options would look something like:

- Don't Convert <-- Current Behavior
- JPEG
- PNG
- TIFF
- .... (etc)

**Comment by JNavas2** [comment]
FYI, [IrfanView](url=https://www.irfanview.com) can batch convert and/or resize, etc.

**Comment by bricelam** [comment]
Image Resizer for Windows is a simple utility for batch resizing images. This feature is outside the scope of this product and won't be added. It aims to do one thing, and to that one thing well.

There are [plenty of great alternatives](https://alternativeto.net/software/irfanview/) out there that can convert images.

Someone could even fork this project and make a sister tool that is all about converting images.
