### ISSUE TITLE
No Access

### ISSUE THREAD

**Issue by jack-d-ripper** [bricelam/ImageResizer#69]
When I try to reduce a bmp I get this message: Access to the path 'C:\\Users\JB\Pictures\Paint\MRBedited (Small).bmp is denied.

**Comment by Bobyl** [comment]
Do you use an antivirus (such as Bitdefender)?
Some of them protects the home folder against modifications.

**Comment by jack-d-ripper** [comment]
Yes, I do. I’ll check it out. Thanks.

**Comment by bricelam** [comment]
I'm not able to reproduce this issue. If someone who is can provide more details about what Image Resizer for Windows should be doing differently, I'd be happy to work with them on a fix.
