### ISSUE TITLE
"Can't resize the following pictures" error

### ISSUE THREAD

**Issue by galijas** [bricelam/ImageResizer#70]
Hello, 

I've been using Image Resizer for a long time and I love it, so thanks for your work.
Today, I've got a pop up for an update, so I downloaded v3.1.0 and installed it (run as admin...).

However, in new version, after i click resize i get this error (see picture attached). I did change some of the sizes, and made a two new ones, if that is relevant...
I had to install old version to get it working again.

![error](https://user-images.githubusercontent.com/38309686/38659303-46bc7838-3e29-11e8-8a5a-3c4fbcfb0772.jpg)

Thanks again, love the new options!

*I tried to resize a picture on a desktop, with a different name than those in error.

**Comment by JNavas2** [comment]
Looks like Registry corruption.
Before installing new version, uninstall old version, _followed by reboot_.
If that doesn't work, you may need to manually remove Registry entries.

**Comment by galijas** [comment]
Did the uninstall, but not the other steps. Will try them!

Thank you very much!


-------- Izvorna poruka --------
Šalje: John Navas <notifications@github.com>
Datum: 12.04.2018. 17:05 (GMT+01:00)
To: bricelam/ImageResizer <ImageResizer@noreply.github.com>
Cc: galijas <galijas_93@hotmail.com>, Author <author@noreply.github.com>
Naslov: Re: [bricelam/ImageResizer] "Can't resize the following pictures" error (#70)


Looks like Registry corruption.
Before installing new version, uninstall old version, followed by reboot.
If that doesn't work, you may need to manually remove Registry entries.

**Comment by bricelam** [comment]
This is caused by the old (3.0) shell extension calling the new (3.1) app. No idea how it happens; I was never able to repro this.

**Comment by bricelam** [comment]
Curios, were you asked to restart after installing? (or told you may need to?)

**Comment by bricelam** [comment]
I'm going to see if there's a way to force File Explorer to unload the old extension during install.

**Comment by galijas** [comment]
Was not asked or told to restart. Forgot to mention, it's working just fine on my second PC.
I'll leave the other pc as it is, so I can test new releases on it.

**Comment by dheif** [comment]
Same here, updated without uninstalling. Did not reboot. Get the following popup when resizing:
![image](https://user-images.githubusercontent.com/8069361/38932472-4b8f0da2-42e4-11e8-8115-f220dfe099db.png)

**Comment by bricelam** [comment]
Hmm... I'm not able to get into this situation without first going through this dialog:

![image](https://user-images.githubusercontent.com/1226749/40582360-7d702786-6128-11e8-860b-c29b3eaf3a1d.png)

**Comment by orestone** [comment]
Mine was resolved after a repair and reboot.

**Comment by bricelam** [comment]
## Moved to Microsoft PowerToys

All future bug fixes, enhancements, and releases of Image Resizer for Windows will be done as part of the Microsoft PowerToys project.

If this is still something you'd like to see done, please follow up on [microsoft/PowerToys](https://github.com/microsoft/PowerToys)
