### ISSUE TITLE
3.1.0 installer name

### ISSUE THREAD

**Issue by JNavas2** [bricelam/ImageResizer#71]
**Congrats on the release! Thank you!**

Installer name is currently _ImageResizerSetup.exe_ which does not indicate the version.
Suggest instead it be named _ImageResizerSetup-3.1.0.exe_ to indicate the version.

**Comment by bricelam** [comment]
This was intentional. (Possibly unwise, but definitely intentional)

**Comment by JNavas2** [comment]
Fair enough, but suggest you reconsider.

**Comment by bricelam** [comment]
The future of releases is unknown. I don't intend to work on Backlog items any time soon (took me five years to complete this release). Give the infrequency, having the version there just felt like clutter.

If translations are added or updated frequently, I'll consider establishing a regular release cadence for them. If it's frequent, I'll definitely add the version back to the filename.

**Comment by bricelam** [comment]
You're in luck. 😄 There's enough bugs to warrant a 3.1.1 release.

You beta test for years, and customers still manage to find bugs as soon as your release. 😑

**Comment by JNavas2** [comment]
Yep! LOL
