### ISSUE TITLE
"Make smaller" and Auto clashing

### ISSUE THREAD

**Issue by BMWBig6** [bricelam/ImageResizer#73]
The default Small, Medium, and Large modes seem to work, but the Custom option no longer seems to work with the latest version.

**Comment by panther2** [comment]
Works fine here... can you give an example?

**Comment by BMWBig6** [comment]
I'm trying to resize an image (jpg) that is 3264x1836 using the "Custom" mode to "Fit" 1920x1920.  When I press "OK" to perform the action, ImageResizer acts like it's working correctly (and even creates a new duplicate file) but it has the same identical dimensions as the original file (no resize was performed).

**Comment by BMWBig6** [comment]
I just tried to create a new size option and it still didn't work.  I even modified one of the default sizes (like "Phone") to 1920x1920 and it didn't work either.  But the original default sizes seem to work fine.

**Comment by bricelam** [comment]
@BMWBig6 that could be a bug. I'll investigate.

**Comment by cfjedimaster** [comment]
I think I'm seeing this as well. I've got 'make smaller only' checked. I'm using Fit, and I specified just 650 for a width, leaving height blank. When I resize, it does nothing.
