### ISSUE TITLE
Suggestion - Show JPEG Quality level in main window

### ISSUE THREAD

**Issue by mvs12** [bricelam/ImageResizer#74]
Just wanted to make a quick suggestion in case anyone else thinks it also might be valuable. Personally I like how flexible ImageResizer is as it allows me to quickly select the resolution depending on what I'll be using it for. Personally, I would find it real useful if in the same main window I could also select the JPEG quality. Most of the time I use 80%, but sometimes I want 100% and sometimes a lot less. 

I was really excited about this version primarily because of the option to change the quality level. However where it's located in the advanced menu doesn't make it too convenient. Having a toggle button whether to show it on the main window or not would be something at least I would greatly appreciate.

Just an idea. Regardless, thank you for the great program! Your work doesn't go unappreciated.

**Comment by mvs12** [comment]
I see your point. But it could be argued both ways. 

I would consider setting the quality as part of resizing. More so considering it's something the program does automatically already during resizing. I'm just saying that instead of being hidden in the advanced menu it might be beneficial for users who are interested in it to be able to see it in the front page alongside the different options for resolutions. After all, resizing an image (space-wise) is a function of resolution as well as compression (JPEG quality). For your typical JPEGs, at least.

**Comment by JNavas2** [comment]
With respect, I don't agree.

**Comment by bricelam** [comment]
As a matter of principle, I refuse to add anything else to the main screen. Deciding to add *Ignore the orientation of pictures* was the hardest thing I ever did. 😉

**Comment by bricelam** [comment]
To illustrate my point, here's what the original XP version looked like:

![imageresizerxp](https://user-images.githubusercontent.com/1226749/38771462-9e466072-3fd8-11e8-90ca-5d87923c887b.png)

And here's what it looks like 15 years later:

![imageresizer31](https://user-images.githubusercontent.com/1226749/38771470-bbd4c890-3fd8-11e8-8d18-cee15eea45d7.png)
