### ISSUE TITLE
Requires delete confirmation for every file when 'resize original' is selected

### ISSUE THREAD

**Issue by TMBW** [bricelam/ImageResizer#75]
When 'Resize the Original Picture (don't create copies) is selected, users have to manually confirm the deletion of each individual original picture. This makes large batch resizing extremely frustrating & time consuming! The previous version didn't do this. Please fix?

**Comment by bricelam** [comment]
Oh wow, it asks for confirmation? lol, that wasn't intentional...

**Comment by TMBW** [comment]
Thanks for the quick reply! I am running Windows 10 build 16299.371.

**Comment by Caldolan** [comment]
HI together - I have Windows Version 10.0.15063 Build 15063. When I take the picture to my Hard-Disk-Drive like C: than I get no request. But If I have a Netfolder like \\SRV\picture than I get also the request for each picture. I hope this is helpful...

**Comment by Caldolan** [comment]
ups A mistake in typing at the netfolder ,-) I mean like **\\**srv\picture

**Comment by Caldolan** [comment]
`\\srv\picture` <- Ok now is right.. Is the first time that I writte on GitHub...

**Comment by revenger2111** [comment]
i have kind of the same problem. when i have the option to delete the original on, it does work but only when i use it for one picture. when i use it for a batch of picture's it just keeps the original

**Comment by bricelam** [comment]
I never see the dialog on my machine, so I'm not entirely sure if this fixed it...

Could someone download and install [this build](https://ci.appveyor.com/project/bricelam/imageresizer/build/1.0.38/artifacts) an confirm that it's fixed?

**Comment by chincherpa** [comment]
V 3.1.1.0 - not fixed
Win10 1709 Build 16299.371

**Comment by Caldolan** [comment]
Unfortunately I see the dialog also with the new build
![grafik](https://user-images.githubusercontent.com/38488686/39124585-350c1b9e-46fc-11e8-9af3-f9ee058a8547.png)

I take this options:
![grafik](https://user-images.githubusercontent.com/38488686/39124594-3e37f4e0-46fc-11e8-861a-fe474575f7b6.png)

**Comment by bricelam** [comment]
OK, I went back to the way it was in 3.0. You can use [this build](https://ci.appveyor.com/project/bricelam/imageresizer/build/1.0.40/artifacts) to confirm it's fixed (uninstall the previous private build before installing).

**Comment by chincherpa** [comment]
It's fixed, thank you very much

**Comment by Caldolan** [comment]
I confirme too - It is fixed. Thank you very much
