### ISSUE TITLE
Could not find file

### ISSUE THREAD

**Issue by pmeebers** [bricelam/ImageResizer#79]
"upgraded" to 3.1.0 today using W10.  When I click on and choose a file, menu appears for resizing.  When I select that it tells me that it "could not find the file"  I have uninstalled previous version, this latest version and reinstalled 2x, same error.  Tried other suggestions from previous posts, no luck.

**Comment by JNavas2** [comment]
Did you _reboot_ after first uninstalling, and _reboot_ again after reinstalling?
It's _important_ to do that.

**Comment by pmeebers** [comment]
Yes I did.  Tx

**Comment by pmeebers** [comment]
Tried what you recommended.  Still says it cannot find the file.   Did the uninstall using REVO, still same results.  Version 3.0 works without issue.     Tx

**Comment by bricelam** [comment]
Can you share a screenshot of the error?

What is the result of running the following inside command prompt?
``` cmd
REG QUERY HKLM\SOFTWARE\BriceLambson\ImageResizer /ve
REG QUERY HKLM\SOFTWARE\WOW6432Node\BriceLambson\ImageResizer /ve
```

Is there a file named ImageResizer.exe under either of the following?
- C:\Program Files\Image Resizer for Windows
- C:\Program Files (x86)\Image Resizer for Windows

**Comment by pmeebers** [comment]
Thank you for your response.  I uninstalled ver 3.0.4802.35565 and installed version 3.1.0.3.  Same error, after I choose a file to resize, and select I get the error file not found.  Please see info you requested in previous message.  


![ir1](https://user-images.githubusercontent.com/38467998/39401108-d3e624c2-4b0b-11e8-8de2-f3cf76440aa2.JPG)
![ir2](https://user-images.githubusercontent.com/38467998/39401109-d3f9b3b6-4b0b-11e8-8fa3-22228c371f2f.JPG)
![ir3](https://user-images.githubusercontent.com/38467998/39401110-d407d612-4b0b-11e8-8387-3608deeb0215.JPG)
![ir4](https://user-images.githubusercontent.com/38467998/39401111-d4168414-4b0b-11e8-8971-e77a7eaffe7d.JPG)
![ir5](https://user-images.githubusercontent.com/38467998/39401112-d425a908-4b0b-11e8-9889-73d0053d48b2.JPG)

**Comment by bricelam** [comment]
Interesting. May be caused by the upper-cased extension. I'll try to repro locally.

**Comment by pmeebers** [comment]
Back to 3.0..works without issue.

**Comment by bricelam** [comment]
I think this is fixed... I'm not able to repro it on the latest codebase.

**Comment by pmeebers** [comment]
Hi Brice.  OP on #79, downloaded 3.1.1 today and it works without issue.  Tx for taking the time to fix this problem.  Meebers
 

Sent: Saturday, May 26, 2018 at 3:17 PM
