### ISSUE TITLE
detected not safe by norton?

### ISSUE THREAD

**Issue by doofie** [bricelam/ImageResizer#81]
hi, i tried to download your executable but norton identified your file as not safe and doesnt allow me to install

**Comment by JNavas2** [comment]
That's a _false positive_, a not uncommon issue with Norton.
And Norton is a waste of money -- free Microsoft anti-malware is all you really need.
But you can temporarily disable Norton to do the install -- see
https://support.norton.com/sp/en/us/home/current/solutions/v116457581_ns_retail_en_us
