### ISSUE TITLE
Option for language

### ISSUE THREAD

**Issue by thoral** [bricelam/ImageResizer#83]
I'd like to have an option to switch the interface language. I would prefer English instead of German. First, because there is a typo in the German GUI ('past' instead of 'passt'). 

Second, and much more important, I don't like it when a target filenames includes the German grapheme 'ß' when altering the filename after scaling e. g.: 
my_image (Groß).jpg

Instead, I would prefer to use a filename like my_image (medium).jpg as before in version 3.0.0.0.

Edit: I just noticed that I can change the suffixes, so issue no. 2 has been resolved...!

Thank you for this very useful tool!

Thorsten

**Comment by bricelam** [comment]
Duplicate of #55

**Comment by thoral** [comment]
Could you please change the typo in the German GUI? ('past'/'passt')

**Comment by bricelam** [comment]
@thoral Sure. You can also review and edit the translation over at https://poeditor.com/join/project/fqkB4t3mez
