### ISSUE TITLE
Pictures that don't need resizing are also resized

### ISSUE THREAD

**Issue by alex-movila** [bricelam/ImageResizer#85]
I want to shrink down some mp3 covers to 500*500. Some covers already have these dimensions.
The result is that these covers are processed once more which results in further quality loss and also grow in data size.
Please implement to skip these files ( optionally: unless we have a configured threshold data size in percentage maybe and we want to encode more efficiently).

**Comment by JNavas2** [comment]
+1

**Comment by bricelam** [comment]
It used to be like that a long time ago, but I got a request to make it always resize because the file size was generally smaller after re-creating.

**Comment by bricelam** [comment]
This could make for a good advanced options checkbox...

**Comment by JNavas2** [comment]
>This could make for a good advanced options checkbox...

Agreed. And I even think the default should be _not_ to resize to same size.
I was a bit shocked to find that it resized images that didn't need resizing,
because _re-compression inevitably reduces quality_.

**Comment by archergod** [comment]
Maybe you can put a check that if Resized Image is bigger in file size, then don't replace the output .. But agree it is more of advance checkbox list feature.

**Comment by bricelam** [comment]
## Moved to Microsoft PowerToys

All future bug fixes, enhancements, and releases of Image Resizer for Windows will be done as part of the Microsoft PowerToys project.

If this is still something you'd like to see done, please follow up on [microsoft/PowerToys](https://github.com/microsoft/PowerToys)
