### ISSUE TITLE
Enhancement Request: Setting to Overwrite Existing Files in Target Folder

### ISSUE THREAD

**Issue by Kelderic** [bricelam/ImageResizer#88]
First off, thank you for this software. I've been using it for a while now and it's really great. I just updated to 3.1 and the ability to specify the new filename template is AWESOME.

I have a feature request though, which would help my workflow, which currently is:

- Image folder with a subfolder for resized thumbnails. Any time image is updated, the new full size replaces the previous full size, then Image Resizer is used to create the new thumbnail in the subfolder.

Right now, when this is done, it doesn't overwrite the existing thumbnail. It just appends {1) to the filename of the new thumbnail.

It would be great to have an option in Advanced Settings to allow for overwriting of existing files in the target folder.

**Comment by bricelam** [comment]
I've always thought **Resize the original pictures** was a bit silly when resizing into a new folder. I think replacing it with **Overwrite existing pictures** in this case makes perfect sense.

**Comment by bricelam** [comment]
## Moved to Microsoft PowerToys

All future bug fixes, enhancements, and releases of Image Resizer for Windows will be done as part of the Microsoft PowerToys project.

If this is still something you'd like to see done, please follow up on [microsoft/PowerToys](https://github.com/microsoft/PowerToys)
