### ISSUE TITLE
Resizer won't resize pictures in "This PC > Pictures"

### ISSUE THREAD

**Issue by alansharkey** [bricelam/ImageResizer#93]
This is weird and it may be just me but I dont know why.

I have a picture "DSCF0720.JPG". It sits at the top level of "My Pictures". If I try and resize it, nothing happens.
If I copy it into a sub directory, everything works as intended.
The file is not read-only or hidden. It;s 1.21Mb in size and is a 2048 x 1536 picture.
I have tried it with other pictures and get the same result - nothing at top level but Ok in a sub directory.

I'm running version 3.1.0 of image resizer.

What else can I tell you?

Alan

**Comment by JNavas2** [comment]
1. Which version of Windows?
1. Does it work if you open the path from the root?

**Comment by alansharkey** [comment]
Close this off. It's a Windows bug in that Windows won't automatically refresh the top level but it will refresh sub directories. When I pressed <F5> the image appeared.

Apologies for wasting your time.

Alan

**Comment by JNavas2** [comment]
It's not just top level -- Windows (8.1) doesn't refresh Desktop either.
It might be a good idea for Image Resizer to force refresh.
