### ISSUE TITLE
Enhancement suggestion: Force Refresh

### ISSUE THREAD

**Issue by JNavas2** [bricelam/ImageResizer#94]
Windows 8.1 Pro x64, Image Resizer 3.1.0
With image on the Desktop, Resize the original pictures
leaves the picture with the original properties.
New properties only appear after manual refresh.
Suggest IR force refresh after resize.
Related: Issue #93

**Comment by bricelam** [comment]
## Moved to Microsoft PowerToys

All future bug fixes, enhancements, and releases of Image Resizer for Windows will be done as part of the Microsoft PowerToys project.

If this is still something you'd like to see done, please follow up on [microsoft/PowerToys](https://github.com/microsoft/PowerToys)
