### ISSUE TITLE
Not an issue, or a request, just a heartfelt thank you!

### ISSUE THREAD

**Issue by ckcelite** [bricelam/ImageResizer#95]
Sorry Brice, I could not find anywhere else to post this, hope it's no problem. I use [ImageResizer](https://github.com/bricelam/ImageResizer) all the time, it's a great help to me and I just wanted to say thank you for the time and effort you put into it!

![image](https://user-images.githubusercontent.com/38842028/39596477-196eab02-4ed8-11e8-8ddf-3d202a8b2644.png)

**Comment by xirbbrix** [comment]
Hear, hear!

**Comment by JNavas2** [comment]
+1

**Comment by ColonelBlimp** [comment]
Let me add my voice to this!

**Comment by bricelam** [comment]
You're welcome! You guys make it worth it.
![no problem thumbs up GIF](https://media.giphy.com/media/Wtinp9UhZ9fEI/giphy.gif)

**Comment by mittus** [comment]
I very happy, that you resume to work with this project!! It's the best programm for work with resizing images, I and all my family use this from 2012 year! THANK YOU!!!!

**Comment by craiglotter** [comment]
+1 - thank you for this brilliantly useful little utility. Makes photo management infinitely easier!

**Comment by yoyoyvr** [comment]
Now, can you submit a PR to get this merged back into Windows 10 where it belongs in the first place? ;-)

**Comment by Torkell** [comment]
The old Windows XP PowerToy doesn't seem to work in Windows 10 (persuaded it to install in compatibility mode but the context menu didn't show up), but I managed to find this instead and it's working perfectly. Thanks!

**Comment by bricelam** [comment]
## Moved to Microsoft PowerToys

All future bug fixes, enhancements, and releases of Image Resizer for Windows will be done as part of the Microsoft PowerToys project.

Thanks again for your support!
